# Generated by vcraft. Do not edit.
# Regenerate with `vcraft build`.

from typing import Any, Sequence

"""Adds two integers and returns the sum."""
def add(a: int, b: int) -> int: ...

"""Greets someone by name.
	Raises ValueError when the name is empty.
"""
def greet(name: str) -> str: ...

"""Divides two floats, refusing a zero divisor."""
def divide(a: float, b: float) -> float: ...

"""Repeats a string n times."""
def repeat(text: str, n: int) -> str: ...

"""Returns nothing."""
def noop() -> None: ...

"""Sums a sequence of integers."""
def total(values: Sequence[Any]) -> int: ...

"""Takes any Python object and returns it unchanged."""
def passthrough(obj: Any) -> Any: ...

"""A counter with state.
	
	Fields must be scalars. A V string inside a Python object would be a pointer
	that V's collector cannot see, because it does not scan memory CPython
	allocated, so the string would be reclaimed while Python still held it. Reach a
	string through a method, which marshals it properly.
"""
class Counter:
    value: int
    step: int
    def increment(self) -> int: ...
    def set_step(self, step: int) -> None: ...
    def double(self) -> None: ...
    @property
    def is_zero(self) -> bool: ...
