# Generated by vcraft. Do not edit.
# Regenerate with `vcraft build`.

from typing import Any, Sequence

"""Adds two integers and returns the sum."""
def add(a: int, b: int) -> int: ...

"""Greets someone by name.
	Raises ValueError when the name is empty.
"""
def greet(name: str) -> str: ...

"""Divides two floats, refusing a zero divisor.
	
	The failure is a ZeroDivisionError rather than a RuntimeError, because Python
	code dividing by zero expects to catch that. See vcraft/errors.v.
"""
def divide(a: float, b: float) -> float: ...

"""Parses an integer, refusing anything else.
	
	An out-of-range value is an OverflowError and a non-digit is a ValueError, which
	are what int() raises for the same inputs.
"""
def parse_int(text: str) -> int: ...

"""Reads past the end of a slice, to show what a V panic looks like from Python.
	
	A V panic would call exit(1) and take the interpreter with it. The generated
	wrapper recovers it and raises RuntimeError instead, so the process survives.
"""
def first_char(text: str) -> str: ...

"""Repeats a string n times."""
def repeat(text: str, n: int) -> str: ...

"""Returns nothing."""
def noop() -> None: ...

"""Sums a sequence of integers."""
def total(values: Sequence[Any]) -> int: ...

"""Takes any Python object and returns it unchanged."""
def passthrough(obj: Any) -> Any: ...

"""A counter with state.
	
	Fields must be scalars. A V string inside a Python object would be a pointer
	that V's collector cannot see, because it does not scan memory CPython
	allocated, so the string would be reclaimed while Python still held it. Reach a
	string through a method, which marshals it properly.
"""
class Counter:
    value: int
    step: int
    def increment(self) -> int: ...
    def set_step(self, step: int) -> None: ...
    def double(self) -> None: ...
    @property
    def is_zero(self) -> bool: ...

"""BoundedCounter inherits Counter's state and adds a limit.
	
	A subclass declares `@[vc_base(Name)]`. Its instances get the base's fields, methods
	and properties as well as its own, and the state block is one value holding the base
	struct followed by this one.
	
	V has no struct inheritance, so `BoundedCounter` names only `limit` and a method of
	the subclass cannot write `c.value`. A method that needs the base's fields reads them
	through `vcraft.load_state`, which is what the generated accessors do.
"""
class BoundedCounter(Counter):
    limit: int
    @property
    def at_limit(self) -> bool: ...
    def bump(self, by: int) -> int: ...
