module vcraft_project

import os

// The PEP 517 backend.
//
// PEP 517 says `pip install .` does not run a script. It reads `[build-system]` from
// `pyproject.toml`, imports the named object, and calls hooks on it. The hooks return
// the *path* of an artefact the frontend has just written, not the bytes.
//
// The backend is a small Python file rather than a V extension, and that is the whole
// design decision. A backend in V would have to be compiled before it could run, which
// means the frontend needs a working V toolchain before it can even resolve a build
// requirement — and resolving build requirements is the step that decides whether V is
// needed at all. It also cannot be a wheel, for the same reason. So the backend is
// text: it locates the `vcraft` binary and runs it, and everything interesting happens
// in the binary.
//
// The generated file is written on every `vcraft new` and `vcraft build`. Writing it
// rather than shipping it in the package means it cannot go stale against the binary it
// calls, and a project that checks it in is carrying a file that describes a version of
// the tool that built it.

// backend_py is the file `pyproject.toml` names.
pub fn backend_py() string {
	return 'vcraft_build.py'
}

// pyproject_toml is the build-system table pointing at it.
//
// `backend-path` is what makes a local file importable without it being installed. It
// is the reason this approach works at all: the frontend adds the project directory to
// `sys.path`, finds the file, and never asks where it came from.
pub fn pyproject_toml() string {
	return '[build-system]\n' +
		'requires = []\n' +
		'build-backend = "vcraft_build"\n' +
		'backend-path = ["."]\n'
}

// write_backend writes `pyproject.toml` and the backend into a project.
//
// Both are rewritten every time rather than only when absent. They describe the tool
// that is building, and a project that upgraded vcraft should get the matching backend
// rather than whichever one it happened to be generated with.
pub fn write_backend(root string) ![]string {
	mut written := []string{}
	manifest := root.trim_right('/') + '/pyproject.toml'
	os.write_file(manifest, pyproject_toml()) or {
		return error('cannot write ${manifest}')
	}
	written << manifest
	backend := root.trim_right('/') + '/' + backend_py()
	os.write_file(backend, backend_source()) or {
		return error('cannot write ${backend}')
	}
	written << backend
	return written
}

// backend_source is the Python that PEP 517 imports.
//
// Deliberately short. Every hook does one thing: run the `vcraft` binary in the
// frontend's directory and return the path it printed. The logic is in the binary,
// where it can be tested against a real project, rather than here where it can only be
// tested against a mock.
fn backend_source() string {
	mut out := '"""The PEP 517 backend for vcraft.\n\n'
	out += 'Generated by `vcraft new` and rewritten on every build. Do not edit.\n\n'
	out += 'Every hook here runs the `vcraft` binary and returns the path of what it\n'
	out += 'wrote, which is what PEP 517 asks for. The build itself happens in the\n'
	out += 'binary: this file locates it, runs it, and reports the result.\n'
	out += '"""\n\n'
	out += 'from __future__ import annotations\n\n'
	out += 'import os\nimport shutil\nimport subprocess\nimport sys\n\n\n'
	out += 'def _vcraft() -> str:\n'
	out += '    """Return the vcraft binary, preferring one on PATH over a sibling.\n\n'
	out += '    A checkout has `bin/vcraft` next to the project and no installed copy, and\n'
	out += '    the binary in the tree is the one whose behaviour matches the backend.\n'
	out += '    """\n'
	out += '    override = os.environ.get("VCRAFT_BIN")\n'
	out += '    if override and os.path.exists(override):\n'
	out += '        return override\n'
	out += '    sibling = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "bin", "vcraft")\n'
	out += '    if os.path.exists(sibling):\n'
	out += '        return sibling\n'
	out += '    found = shutil.which("vcraft")\n'
	out += '    if found:\n'
	out += '        return found\n'
	out += '    raise RuntimeError(\n'
	out += '        "vcraft is not on PATH; put it there, set VCRAFT_BIN, or build from a checkout"\n'
	out += '    )\n\n\n'
	out += 'def _run(*args: str) -> str:\n'
	out += '    """Run vcraft and return the last line of its output, which is the path.\n\n'
	out += '    The last line is the contract: `vcraft build` and `vcraft sdist` both end with\n'
	out += '    the artefact they wrote, so a backend does not have to guess at a name.\n'
	out += '    """\n'
	out += '    env = dict(os.environ)\n'
	out += '    # The backend may be invoked from a copy of the project that is not a\n'
	out += '    # checkout of this tool, so the binary has to be named rather than inferred\n'
	out += '    # from where the project sits.\n'
	out += '    env.setdefault("VCRAFT_BIN", _vcraft())\n'
	out += '    result = subprocess.run([_vcraft(), *args], capture_output=True, text=True, env=env)\n'
	out += '    if result.returncode != 0:\n'
	out += '        raise RuntimeError(result.stderr.strip() or result.stdout.strip())\n'
	out += '    lines = [line for line in result.stdout.strip().splitlines() if line.strip()]\n'
	out += '    if not lines:\n'
	out += '        raise RuntimeError("vcraft produced no output")\n'
	out += '    # The artefact is the only line ending in the extension it built. Taking the\n'
	out += '    # last line instead picks up the summary vcraft prints after it, and PEP 517\n'
	out += '    # then tries to open a wheel whose name is a file size.\n'
	out += '    for line in lines:\n'
	out += '        if line.endswith(".whl") or line.endswith(".tar.gz"):\n'
	out += '            return line\n'
	out += '    return lines[-1]\n\n\n'
	out += 'def build_wheel(wheel_directory, config_settings=None, metadata_directory=None) -> str:\n'
	out += '    """Build a wheel and return its file name, which is what PEP 517 wants.\n\n'
	out += '    PEP 517 asks for the *name*, not the path, and pip joins it onto the\n'
	out += '    directory it chose. Returning the full path makes pip join it a second\n'
	out += '    time, and the resulting error names a path with the directory inside\n'
	out += '    itself.\n'
	out += '    """\n'
	out += '    produced = _run("build", "--release", "--out-dir", wheel_directory)\n'
	out += '    return os.path.basename(produced)\n\n\n'
	out += 'def build_sdist(sdist_directory, config_settings=None) -> str:\n'
	out += '    produced = _run("sdist", "--out-dir", sdist_directory)\n'
	out += '    return os.path.basename(produced)\n\n\n'
	out += 'def get_requires_for_build_wheel(config_settings=None) -> list[str]:\n'
	out += '    # vcraft compiles through V and links nothing, so there is nothing to install\n'
	out += '    # before the build. The compiler itself is a host tool rather than a Python\n'
	out += '    # dependency, and PEP 517 has no way to ask for one.\n'
	out += '    return []\n\n\n'
	out += 'def get_requires_for_build_sdist(config_settings=None) -> list[str]:\n'
	out += '    return []\n\n\n'
	out += 'def prepare_metadata_for_build_wheel(metadata_directory, config_settings=None) -> str:\n'
	out += '    """Return the .dist-info directory name, as PEP 517 requires.\n\n'
	out += '    The hook is optional and PEP 517 allows a backend to leave it out, but pip\n'
	out += '    calls it when it is there and uses the answer without checking that it is a\n'
	out += '    string. Returning None gives a TypeError deep inside pip\'s os.path.join,\n'
	out += '    with nothing in the traceback pointing at this line.\n\n'
	out += '    So the metadata comes from building the wheel and lifting the .dist-info out\n'
	out += '    of it. That is wasteful for a frontend which wanted to skip the build, and\n'
	out += '    cheaper than a second implementation of the metadata that would eventually\n'
	out += '    disagree with the first.\n'
	out += '    """\n'
	out += '    import glob\n'
	out += '    import tempfile\n'
	out += '    import zipfile\n\n'
	out += '    with tempfile.TemporaryDirectory() as staging:\n'
	out += '        _run("build", "--release", "--out-dir", staging)\n'
	out += '        built = glob.glob(os.path.join(staging, "*.whl"))\n'
	out += '        if not built:\n'
	out += '            raise RuntimeError("vcraft produced no wheel")\n'
	out += '        # A wheel name is `name-version-tag-tag-platform.whl`, so the\n'
	out += '        # distribution and version are everything before the last three parts.\n'
	out += '        # rsplit with a count of two stops one short and yields\n'
	out += '        # `name-version-cp314`, which pip then reads as the *version* and rejects\n'
	out += '        # with "Invalid version".\n'
	out += '        dist_info = os.path.basename(built[0])[:-len(".whl")].rsplit("-", 3)[0]\n'
	out += '        dist_info += ".dist-info"\n'
	out += '        target = os.path.join(metadata_directory, dist_info)\n'
	out += '        os.makedirs(target, exist_ok=True)\n'
	out += '        with zipfile.ZipFile(built[0]) as archive:\n'
	out += '            for entry in archive.namelist():\n'
	out += '                if ".dist-info/" not in entry:\n'
	out += '                    continue\n'
	out += '                out = os.path.join(target, entry.split(".dist-info/", 1)[1])\n'
	out += '                os.makedirs(os.path.dirname(out), exist_ok=True)\n'
	out += '                with archive.open(entry) as src, open(out, "wb") as dst:\n'
	out += '                    dst.write(src.read())\n'
	out += '        return dist_info\n'
	return out
}
