#!/usr/bin/env python3
"""Tests for the code generator, end to end.

Builds the `examples/hello` project through `scripts/build-example.sh`, which runs
the real generator and then the real compiler, and then exercises the module it
produced. Nothing but the standard library is needed:

    ./scripts/build-example.sh hello hello_native
    python3 tests/codegen/test_codegen.py
"""

import subprocess
import sys
import sysconfig
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
PROJECT = ROOT / "examples" / "hello"
PYTHON_DIR = PROJECT / "python"
GLUE = PROJECT / "src" / "_vcraft_generated.v"
STUBS = PYTHON_DIR / "hello_native" / "_stubs.pyi"
PACKAGE = "hello_native"


class Suite:
    def __init__(self) -> None:
        self.passed = 0
        self.failures: list[str] = []

    def check(self, label: str, condition: bool, detail: str = "") -> None:
        if condition:
            self.passed += 1
            print(f"  ok   {label}")
        else:
            print(f"  FAIL {label} {detail}")
            self.failures.append(label)

    def equal(self, label: str, got, expected) -> None:
        self.check(label, got == expected, f"got {got!r}, want {expected!r}")

    def raises(self, label: str, exc_type, needle: str, call) -> None:
        try:
            result = call()
        except exc_type as exc:
            self.check(label, needle in str(exc), f"got {exc!r}")
        except Exception as exc:  # noqa: BLE001
            self.check(label, False, f"raised {type(exc).__name__}: {exc}")
        else:
            self.check(label, False, f"returned {result!r}, no exception")


def build() -> None:
    print("building the example")
    result = subprocess.run(
        [str(ROOT / "scripts" / "build-example.sh"), "hello", PACKAGE],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(result.stdout[-3000:])
        print(result.stderr[-3000:])
        raise SystemExit("build failed")


def main() -> int:
    build()
    t = Suite()

    print("generated files")
    t.check("glue written", GLUE.exists())
    t.check("stub written", STUBS.exists())
    glue = GLUE.read_text() if GLUE.exists() else ""
    t.check("glue is marked generated", "Code generated by vcraft" in glue)
    t.check("glue exports PyInit", "@[export: 'PyInit_hello_native']" in glue)
    t.check("glue is in the user module", "module hello_native" in glue)
    t.check("every annotated function is wrapped",
            glue.count("add_function_owned") == 7,
            f"found {glue.count('add_function_owned')}")

    print("annotations")
    t.check("vc_fn is exported", "'add', voidptr(vcraft_generated__wrap_add)" in glue)
    t.check("vc_raw keeps the signature", "arg0 := vcraft.from_py_voidptr(" in glue)
    t.check("no namespace annotations remain", "@[vc." not in glue)

    print("result handling")
    t.check("plain result is assigned", "result = add(arg0, arg1)" in glue)
    t.check("!T result uses error propagation",
            "vcraft.raise_from_error(err)" in glue)
    t.check("void result returns None", "vcraft.to_py_none().ptr" in glue)
    t.check("panic guard is inlined", "if message := recover()" in glue)
    t.check("guard message is escaped", "panic in V code: \\${message}" in glue
            or "panic in V code: ${message}" in glue)

    print("docstrings and signatures")
    t.check("module docstring is a literal",
            "vcraft.new_module('hello_native', '" in glue)
    t.check("signature text emitted", "'add(a: int, b: int) -> int'" in glue)
    t.check("void signature says None", "'noop() -> None'" in glue)
    stubs = STUBS.read_text() if STUBS.exists() else ""
    t.check("stub has add", "def add(a: int, b: int) -> int: ..." in stubs)
    t.check("stub has the docstring", "Adds two integers" in stubs)
    t.check("stub types the sequence", "values: Sequence[Any]" in stubs)

    print("module behaviour")
    sys.path.insert(0, str(PYTHON_DIR))
    import hello_native as h

    t.check("module docstring", "Adds two integers" in (h.__doc__ or ""))
    t.equal("add", h.add(2, 3), 5)
    t.equal("add negative", h.add(-4, 4), 0)
    t.equal("greet", h.greet("world"), "Hello, world!")
    t.equal("divide", h.divide(7.0, 2.0), 3.5)
    t.equal("repeat", h.repeat("ab", 3), "ababab")
    t.check("noop returns None", h.noop() is None)
    t.equal("total over a list", h.total([1, 2, 3, 4]), 10)
    t.equal("total over a tuple", h.total((5, 5)), 10)
    t.equal("total of empty", h.total([]), 0)
    t.equal("text signature", h.add.__doc__, "add(a: int, b: int) -> int")

    print("raw escape hatch")
    sentinel = [1, 2, 3]
    t.check("raw returns the same object", h.passthrough(sentinel) is sentinel)
    t.check("raw survives the call", h.passthrough(sentinel) == sentinel)

    print("errors")
    t.raises("V error", RuntimeError, "name must not be empty", lambda: h.greet(""))
    t.raises("V error from a float function", RuntimeError, "division by zero",
             lambda: h.divide(1.0, 0.0))
    t.raises("too few arguments", TypeError, "takes 2 positional",
             lambda: h.add(1))
    t.raises("too many arguments", TypeError, "takes at most", lambda: h.add(1, 2, 3))
    t.raises("wrong argument type", TypeError, "expected int", lambda: h.add("x", 1))
    t.raises("bool is not an int", TypeError, "expected int", lambda: h.add(True, 1))
    t.raises("wrong string type", TypeError, "expected str", lambda: h.greet(5))
    t.raises("sequence expected", TypeError, "expected a sequence",
             lambda: h.total("ab"))
    t.raises("element type checked", TypeError, "expected int", lambda: h.total([1, "x"]))
    t.raises("integer overflow", OverflowError, "out of range", lambda: h.add(2**64, 1))

    print("still alive after all of that")
    t.equal("arithmetic", h.add(20, 22), 42)
    t.equal("strings", h.repeat("-", 3), "---")

    print("symbol table")
    import subprocess as sp

    suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
    extension = next(iter(PYTHON_DIR.glob(f"{PACKAGE}*.so")), None)
    if extension is not None:
        out = sp.run(["nm", "-D", "--defined-only", str(extension)],
                     capture_output=True, text=True).stdout
        exported = {
            line.split()[-1]
            for line in out.splitlines()
            if len(line.split()) == 3 and line.split()[1] in ("T", "D", "B", "R", "W")
        }
        allowed = {f"PyInit_{PACKAGE}", "_v_interface_exports"}
        t.check("only PyInit is exported", exported <= allowed,
                f"extra: {sorted(exported - allowed)}")
        t.check("extension suffix", extension.name.endswith(suffix), extension.name)

    print()
    if t.failures:
        print(f"{len(t.failures)} failure(s): {', '.join(t.failures)}")
        return 1
    print(f"all {t.passed} checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
