#!/usr/bin/env python3
"""Tests for the code generator, end to end.

Builds the `examples/hello` project through `scripts/build-example.sh`, which runs
the real generator and then the real compiler, and then exercises the module it
produced. Nothing but the standard library is needed:

    ./scripts/build-example.sh hello hello_native
    python3 tests/codegen/test_codegen.py
"""

import gc
import subprocess
import sys
import sysconfig
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
PROJECT = ROOT / "examples" / "hello"
PYTHON_DIR = PROJECT / "python"
GLUE = PROJECT / "src" / "_vcraft_generated.v"
STUBS = PYTHON_DIR / "hello_native" / "_stubs.pyi"
PACKAGE = "hello_native"


class Suite:
    def __init__(self) -> None:
        self.passed = 0
        self.failures: list[str] = []

    def check(self, label: str, condition: bool, detail: str = "") -> None:
        if condition:
            self.passed += 1
            print(f"  ok   {label}")
        else:
            print(f"  FAIL {label} {detail}")
            self.failures.append(label)

    def equal(self, label: str, got, expected) -> None:
        self.check(label, got == expected, f"got {got!r}, want {expected!r}")

    def raises(self, label: str, exc_type, needle: str, call) -> None:
        try:
            result = call()
        except exc_type as exc:
            self.check(label, needle in str(exc), f"got {exc!r}")
        except Exception as exc:  # noqa: BLE001
            self.check(label, False, f"raised {type(exc).__name__}: {exc}")
        else:
            self.check(label, False, f"returned {result!r}, no exception")


def build() -> None:
    print("building the example")
    result = subprocess.run(
        [str(ROOT / "scripts" / "build-example.sh"), "hello", PACKAGE],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(result.stdout[-3000:])
        print(result.stderr[-3000:])
        raise SystemExit("build failed")


def main() -> int:
    build()
    t = Suite()

    print("generated files")
    t.check("glue written", GLUE.exists())
    t.check("stub written", STUBS.exists())
    glue = GLUE.read_text() if GLUE.exists() else ""
    t.check("glue is marked generated", "Code generated by vcraft" in glue)
    t.check("glue exports PyInit", "@[export: 'PyInit_hello_native']" in glue)
    t.check("glue is in the user module", "module hello_native" in glue)
    t.check("every annotated function is wrapped",
            glue.count("add_function_owned") == 23,
            f"found {glue.count('add_function_owned')}")

    print("annotations")
    t.check("vc_fn is exported", "'add', voidptr(vcraft_generated__wrap_add)" in glue)
    t.check("vc_raw keeps the signature", "arg0 := vcraft.from_py_voidptr(" in glue)
    t.check("no namespace annotations remain", "@[vc." not in glue)

    print("result handling")
    t.check("plain result is assigned", "result = add(arg0, arg1)" in glue)
    t.check("!T result uses error propagation",
            "vcraft.raise_from_error(err)" in glue)
    t.check("void result returns None", "vcraft.to_py_none().ptr" in glue)
    t.check("panic guard is inlined", "if message := recover()" in glue)
    t.check("guard message is escaped", "panic in V code: \\${message}" in glue
            or "panic in V code: ${message}" in glue)

    print("docstrings and signatures")
    t.check("module docstring is a literal",
            "vcraft.new_module('hello_native', '" in glue)
    t.check("signature text emitted", "'add(a: int, b: int) -> int'" in glue)
    t.check("void signature says None", "'noop() -> None'" in glue)
    stubs = STUBS.read_text() if STUBS.exists() else ""
    t.check("stub has add", "def add(a: int, b: int) -> int: ..." in stubs)
    t.check("stub has the docstring", "Adds two integers" in stubs)
    t.check("stub types the sequence", "values: Sequence[Any]" in stubs)

    print("module behaviour")
    sys.path.insert(0, str(PYTHON_DIR))
    import hello_native as h

    t.check("module docstring", "Adds two integers" in (h.__doc__ or ""))
    t.equal("add", h.add(2, 3), 5)
    t.equal("add negative", h.add(-4, 4), 0)
    t.equal("greet", h.greet("world"), "Hello, world!")
    t.equal("divide", h.divide(7.0, 2.0), 3.5)
    t.equal("repeat", h.repeat("ab", 3), "ababab")
    t.check("noop returns None", h.noop() is None)
    t.equal("total over a list", h.total([1, 2, 3, 4]), 10)
    t.equal("total over a tuple", h.total((5, 5)), 10)
    t.equal("total of empty", h.total([]), 0)
    t.equal("text signature", h.add.__doc__, "add(a: int, b: int) -> int")

    print("sequence arguments")
    t.equal("an i64 sequence", h.total64([2**40, 1]), 2**40 + 1)
    t.equal("an i64 tuple", h.total64((3, 4)), 7)
    t.equal("a float sequence", h.mean([1.0, 2.0, 6.0]), 3.0)
    t.equal("ints in a float sequence", h.mean([1, 2.0, 3]), 2.0)
    t.equal("an empty float sequence", h.mean([]), 0.0)
    t.raises("a bad item after good ones", TypeError, "expected float",
             lambda: h.mean([1.0, 2.0, "x"]))
    t.raises("an int subclass is read the slow way", TypeError, "expected int",
             lambda: h.total64([1, True]))
    t.raises("an item too large for 64 bits", OverflowError, "out of range",
             lambda: h.total64([1, 2**64]))
    # Each item read used to keep a reference nobody released, so the items of a
    # temporary list were never freed.
    item = 12345.5
    before = sys.getrefcount(item)
    for _ in range(50):
        h.mean([item] * 10)
        h.total([7] * 10)
    t.equal("reading a sequence keeps no reference", sys.getrefcount(item), before)

    print("returned lists and objects")
    # Each of these failed to build before: a `[]T` result called `to_py_list` with one
    # argument, a `PyObj` result crashed the generator, and a `voidptr` result took
    # `.ptr` of a pointer.
    t.check("a list of numbers is built in one pass",
            "vcraft.to_py_i64_list(result)" in glue)
    t.check("any other list is boxed per element",
            "vcraft.to_py_list(result, fn (x string) vcraft.PyObj" in glue)
    t.equal("an i64 list", h.count_up(4), [0, 1, 2, 3])
    t.equal("an empty list", h.count_up(0), [])
    t.equal("a string list", h.words("hola qué tal"), ["hola", "qué", "tal"])
    t.equal("a float list", h.halves([1, 3]), [0.5, 1.5])
    t.equal("an int list", h.squares(3), [0, 1, 4])
    t.equal("an i64 list at full width", h.count_up(2)[-1] + 2**40, 2**40 + 1)
    t.equal("a PyObj result", h.boxed(2**40), [2**40])
    t.check("a PyObj signature", h.boxed.__doc__.startswith("boxed(n: int) -> Any"),
            h.boxed.__doc__)
    probe = object()
    before = sys.getrefcount(probe)
    for _ in range(100):
        h.identity(probe)
    t.check("a voidptr result is the same object", h.identity(probe) is probe)
    t.equal("a voidptr result keeps the count", sys.getrefcount(probe), before)
    for _ in range(100):
        h.boxed(1)
    gc.collect()
    held = h.boxed(1)
    # An upper bound rather than an exact count: the bug this guards handed the
    # caller a second reference on top of the owned one, which read 3 here. `== 2`
    # stopped holding on CPython 3.14, which elides some refcount traffic, so the
    # same owned-once list reads 2 on older versions and 1 on 3.14 (and on 3.14.0
    # even a stored and an inline reference disagree). A leak on an eliding
    # interpreter is invisible to refcounting; the benchmark's kept/leak
    # scenarios are the backstop there.
    refs = sys.getrefcount(held)
    t.check("a PyObj result is owned once", refs <= 2, f"got {refs}")

    print("i64 fields")
    tally = h.Tally()
    tally.sum = 2**40
    t.equal("an i64 field holds 64 bits", tally.sum, 2**40)
    t.equal("an i64 field in the repr", repr(tally), f"Tally(sum: {2**40})")
    tally = h.Tally()
    t.raises("a method can panic", RuntimeError, "failed after writing",
             lambda: tally.add_then_fail(5))
    t.equal("a method works in place, so a write before a panic stays", tally.sum, 5)

    print("collector")
    # Enough allocation to run V's collector some five hundred times: `repeat` builds
    # its result by concatenation, a few hundred KiB per call. On macOS the runtime
    # registers the module's own data as the collector's only static roots, so a root it
    # missed would show up here as a V value freed while still in use: a wrong result,
    # an error that loses its message, or a crash.
    wrong = 0
    for i in range(3_000):
        if h.repeat("ab", 400) != "ab" * 400:
            wrong += 1
        if h.greet(f"n{i}") != f"Hello, n{i}!":
            wrong += 1
        if h.words(f"a b{i}") != ["a", f"b{i}"]:
            wrong += 1
        if i % 10 == 0:
            try:
                h.parse_int("x")
                wrong += 1
            except ValueError as exc:
                wrong += "invalid literal" not in str(exc)
    t.equal("values survive hundreds of collections", wrong, 0)

    print("raw escape hatch")
    sentinel = [1, 2, 3]
    t.check("raw returns the same object", h.passthrough(sentinel) is sentinel)
    t.check("raw survives the call", h.passthrough(sentinel) == sentinel)

    print("errors")
    t.raises("V error", RuntimeError, "name must not be empty", lambda: h.greet(""))
    # `divide` names ZeroDivisionError rather than letting it fall back to
    # RuntimeError, so `except ZeroDivisionError` around a call into V keeps working.
    t.raises("V error from a float function", ZeroDivisionError, "division by zero",
             lambda: h.divide(1.0, 0.0))
    t.raises("too few arguments", TypeError, "takes 2 positional",
             lambda: h.add(1))
    t.raises("too many arguments", TypeError, "takes at most", lambda: h.add(1, 2, 3))
    t.raises("wrong argument type", TypeError, "expected int", lambda: h.add("x", 1))
    t.raises("bool is not an int", TypeError, "expected int", lambda: h.add(True, 1))
    t.raises("wrong string type", TypeError, "expected str", lambda: h.greet(5))
    t.raises("sequence expected", TypeError, "expected a sequence",
             lambda: h.total("ab"))
    t.raises("element type checked", TypeError, "expected int", lambda: h.total([1, "x"]))
    t.raises("integer overflow", OverflowError, "out of range", lambda: h.add(2**64, 1))

    print("still alive after all of that")
    t.equal("arithmetic", h.add(20, 22), 42)
    t.equal("strings", h.repeat("-", 3), "---")

    print("errors")
    t.equal("result value", h.divide(10.0, 4.0), 2.5)
    t.raises("domain error maps to its own type", ZeroDivisionError,
             "division by zero", lambda: h.divide(1.0, 0.0))
    t.equal("parse_int", h.parse_int("1234"), 1234)
    t.raises("value error", ValueError, "invalid literal",
             lambda: h.parse_int("12a4"))
    t.raises("overflow error", OverflowError, "too large",
             lambda: h.parse_int("9" * 25))
    t.raises("an anonymous error stays a RuntimeError", RuntimeError,
             "name must not be empty", lambda: h.greet(""))
    t.raises("argument type error", TypeError, "expected str",
             lambda: h.greet(123))
    t.raises("arity error", TypeError, "positional argument",
             lambda: h.add(1))

    print("panics")
    t.check("a recovered panic raises", True)
    try:
        h.first_char("")
    except RuntimeError as exc:
        t.check("panic message names the cause", "out of bounds" in str(exc), str(exc))
        t.check("panic names the V frame", "panic in V code" in str(exc), str(exc))
    else:
        t.check("a recovered panic raises", False, "no exception")
    # The point of recovering: the interpreter is still usable afterwards, and the
    # extension is not left with a half-written result or a stale exception.
    t.equal("interpreter survives", h.add(2, 3), 5)
    t.equal("extension still works", h.parse_int("7"), 7)
    t.equal("no panic state leaks", h.greet("Ana"), "Hello, Ana!")

    print("class")
    counter = h.Counter()
    t.check("instance repr", repr(counter) == "Counter(value: 0, step: 1)", repr(counter))
    t.check("class name", h.Counter.__name__ == "Counter", h.Counter.__name__)
    t.check("qualified name", h.Counter.__qualname__ == "Counter", h.Counter.__qualname__)
    t.check("module", h.Counter.__module__ == "hello_native", h.Counter.__module__)
    t.check("default field", counter.value == 0, counter.value)
    # Each call is bound before the check, because passing the call itself as the
    # failure detail would run it twice and move the number being asserted.
    first = counter.increment()
    t.check("no-arg method", first == 1, first)
    second = counter.increment()
    t.check("method mutates state", second == 2, second)
    counter.double()
    t.check("second no-arg method", counter.value == 4, counter.value)
    t.check("property reads", counter.is_zero is False, counter.is_zero)
    counter.value = 100
    t.check("field is writable", counter.value == 100, counter.value)
    counter.set_step(4)
    stepped = counter.increment()
    t.check("method with one argument", stepped == 104, stepped)
    t.check("class attributes", sorted(
        n for n in dir(h.Counter) if not n.startswith("_")) ==
        ["double", "increment", "is_zero", "set_step", "step", "value"])
    t.check("instances are distinct",
            h.Counter().value == 0 and h.Counter().value == 0)
    t.check("isinstance", isinstance(counter, h.Counter))
    t.check("subclassable", issubclass(h.Counter, object))
    t.raises("constructor takes no arguments", TypeError, "takes no arguments",
             lambda: h.Counter(1))
    t.raises("setter rejects a wrong type", TypeError, "expected int",
             lambda: setattr(counter, "value", "nope"))
    t.raises("fields cannot be deleted", AttributeError, "cannot be deleted",
             lambda: delattr(counter, "value"))
    t.check("rejected assignment changes nothing", counter.value == 104, counter.value)

    print("class docstrings")
    t.check("class docstring", h.Counter.__doc__.startswith("A counter with state."),
            h.Counter.__doc__)
    t.check("method docstring",
            h.Counter.increment.__doc__ == "increment adds step to value and returns the new total.",
            h.Counter.increment.__doc__)
    t.check("property docstring",
            h.Counter.is_zero.__doc__ == "is_zero reports whether the value is still zero.",
            h.Counter.is_zero.__doc__)
    t.check("field docstring", h.Counter.value.__doc__ == "value is the running total.",
            h.Counter.value.__doc__)

    print("class stub")
    stub = STUBS.read_text() if STUBS.exists() else ""
    t.check("class is declared", "class Counter:" in stub)
    t.check("fields are attributes", "    value: int" in stub, stub[-400:])
    t.check("methods are declared", "    def increment(self) -> int: ..." in stub)
    t.check("property is decorated", "    @property\n" in stub)
    t.check("class docstring reaches the stub", "A counter with state." in stub)

    print("class operators")
    a = h.Counter()
    b = h.Counter()
    t.check("equal by value", (a == b) is True, repr(a == b))
    t.check("not-equal is the negation", (a != b) is False, repr(a != b))
    a.increment()
    t.check("different values are not equal", (a == b) is False)
    t.check("and not-equal", (a != b) is True)
    t.check("hash agrees with equality", hash(a) != hash(b),
            f"{hash(a)} == {hash(b)} for unequal values")
    b.increment()
    t.check("equal again", (a == b) is True)
    t.check("hash agrees when equal", hash(a) == hash(b),
            f"{hash(a)} != {hash(b)} for equal values")
    # The dict and set cases are the point of pairing __eq__ with __hash__: a value
    # comparison with an identity hash misses every lookup without an error.
    keyed = {a: "found"}
    t.check("a dict finds an equal key", keyed.get(b) == "found", str(keyed.get(b)))
    t.check("a set deduplicates equal values", len({a, b}) == 1, str(len({a, b})))
    t.check("a set holds unequal values", len({a, h.Counter()}) == 2)
    # `==` against another type must be False rather than a TypeError, which is what
    # returning NotImplemented buys.
    t.check("equal to an int is False", (a == 5) is False, repr(a == 5))
    t.check("not equal to an int is True", (a != 5) is True)
    try:
        a < b
    except TypeError as exc:
        t.check("ordering raises TypeError", "not supported" in str(exc), str(exc))
    else:
        t.check("ordering raises TypeError", False, "no exception")
    t.check("a subclass is still an instance", isinstance(h.Counter(), h.Counter))

    print("inheritance")
    # A subclass declares `@[vc_base(Name)]`. What Python sees has to be ordinary
    # inheritance: one base, the base's attributes present, the subclass's own present too,
    # and a method that reaches the base's state and writes through to the instance.
    t.check("the subclass exists", hasattr(h, "BoundedCounter"))
    bounded = h.BoundedCounter()
    t.check("the base is the declared one",
            [t.__name__ for t in h.BoundedCounter.__mro__] ==
            ["BoundedCounter", "Counter", "object"],
            [t.__name__ for t in h.BoundedCounter.__mro__])
    t.check("__bases__ names it", h.BoundedCounter.__bases__ == (h.Counter,),
            h.BoundedCounter.__bases__)
    t.check("an instance is an instance of the base", isinstance(bounded, h.Counter))
    t.check("and not the other way round", not isinstance(h.Counter(), h.BoundedCounter))
    t.check("issubclass agrees", issubclass(h.BoundedCounter, h.Counter))

    t.check("inherited field reads", bounded.value == 0 and bounded.step == 1,
            (bounded.value, bounded.step))
    t.check("own field reads", bounded.limit == 0, bounded.limit)
    t.check("the base's constructor ran", bounded.step == 1, bounded.step)

    t.check("inherited setter writes", (setattr(bounded, "step", 3), bounded.step == 3)[1])
    t.check("own setter writes", (setattr(bounded, "limit", 10), bounded.limit == 10)[1])
    # step was set to 3 and value is still 0, so the base's own arithmetic is what
    # decides these numbers: increment adds step, double doubles, bump adds its argument.
    t.check("inherited method mutates the base's field",
            bounded.increment() == 3, bounded.value)
    t.check("inherited method sees its own write", bounded.double() is None
            and bounded.value == 6, bounded.value)
    t.check("inherited property", bounded.is_zero is False)

    t.check("the subclass's own method reads its own field",
            bounded.bump(4) == 10, bounded.value)
    t.check("and the base's field through it", bounded.value == 10, bounded.value)
    t.check("the subclass's own property", bounded.at_limit is True)
    t.raises("the subclass's method can fail", ValueError, "would pass its limit",
             lambda: bounded.bump(99))
    t.check("a refused call changes nothing", bounded.value == 10, bounded.value)

    t.check("repr lists the inherited fields first",
            repr(bounded) == "BoundedCounter(value: 10, step: 3, limit: 10)", repr(bounded))

    # The interesting failure mode: a method of a subclass that writes the base's state
    # through the published pointer. If the trampoline wrote the state back before the
    # write, or never wrote it back, this is where it shows.
    other = h.BoundedCounter()
    other.limit = 4
    other.bump(4)
    t.check("the write reaches the instance", other.value == 4, other.value)
    t.check("and does not touch the first instance", bounded.value == 10, bounded.value)
    t.check("the base's field survives a repr", repr(other).endswith("limit: 4)"), repr(other))

    # A subclass of a subclass, and one written in Python on top of both.
    class PySub(h.BoundedCounter):
        pass

    py = PySub()
    py.limit = 6
    t.check("a Python subclass is an instance of the V base",
            isinstance(py, h.Counter) and isinstance(py, h.BoundedCounter))
    t.check("it runs the base's constructor", py.step == 1, py.step)
    py.increment()
    t.check("it can call the base's method", py.value == 1, py.value)
    t.check("it can call the subclass's method", py.bump(2) == 3, py.value)
    t.check("the subclass's field survives too", py.limit == 6, py.limit)
    t.raises("and its errors reach Python", ValueError, "would pass its limit",
             lambda: py.bump(99))

    print("inheritance in the generated file")
    t.check("the state struct nests the base", "struct BoundedCounterState {" in glue,
            "no BoundedCounterState")
    t.check("the base's state is the type of the base field",
            "base Counter" in glue, "the base field is not the base's state")
    t.check("the subclass's own struct is the other half",
            "self BoundedCounter" in glue)
    t.check("the base tuple is built at run time",
            "vcraft.tuple_of_one(g_vc_type_counter)" in glue)
    t.check("the base level is published", "vcraft.publish_base(1," in glue)
    t.check("the chain is restored on the way out", "vcraft.leave_state(previous)" in glue)
    # One per trampoline that works on a subclass's state, and none in a trampoline of a
    # class with no base: there is no generation above it to point at.
    loaders = glue.count("mut state := unsafe { &BoundedCounterState(")
    t.check("one published level per subclass trampoline",
            glue.count("publish_base(1,") == loaders,
            f"{glue.count('publish_base(1,')} published, {loaders} trampolines")
    t.check("the stub declares the base",
            "class BoundedCounter(Counter):" in stub, stub[-600:])

    print("references and cycles")
    # A `@[vc_ref]` field holds a strong reference, which is the whole reason a cycle can
    # exist at all. Everything here is about the ownership of that reference: the count it
    # holds, the count `tp_clear` and `tp_dealloc` give back, and whether the collector
    # can actually free a pair that points at each other.
    pair = h.Pair()
    peer = h.Pair()
    t.equal("an unset reference reads as None", pair.other(), None)
    t.check("and prints as None", repr(pair) == "Pair(tag: 0, peer: None)", repr(pair))

    before = sys.getrefcount(peer)
    pair.peer = peer
    t.check("the field holds the object it was given", pair.peer is peer)
    t.check("and counts a reference of its own",
            sys.getrefcount(peer) == before + 1, sys.getrefcount(peer) - before)

    t.raises("a reference field is type checked", TypeError, "must be a Pair",
             lambda: setattr(pair, "peer", 5))
    t.check("a rejected assignment changes nothing", pair.peer is peer)
    t.raises("a reference field cannot be deleted", AttributeError, "cannot be deleted",
             lambda: delattr(pair, "peer"))

    pair.peer = None
    t.check("None clears the field", pair.peer is None)
    t.check("and gives the reference back", sys.getrefcount(peer) == before,
            sys.getrefcount(peer) - before)
    t.check("the object is still alive", repr(peer) == "Pair(tag: 0, peer: None)",
            repr(peer))

    pair.peer = peer
    pair.peer = peer
    t.check("assigning the same object twice counts once",
            sys.getrefcount(peer) == before + 1, sys.getrefcount(peer) - before)
    pair.peer = None
    t.check("and clearing it once gives it all back", sys.getrefcount(peer) == before,
            sys.getrefcount(peer) - before)

    # A method that stores a borrowed pointer has to retain it. `link` does, so the peer
    # stays alive as long as the pair does.
    left = h.Pair()
    right = h.Pair()
    right_before = sys.getrefcount(right)
    left.link(right)
    t.check("a method can store a reference", left.peer is right)
    t.check("and the method retained it", sys.getrefcount(right) == right_before + 1,
            sys.getrefcount(right) - right_before)

    # The cycle. Neither instance is reachable from Python once both names are gone, and
    # each holds the other's last reference, so only the collector can free them.
    left.tag = 1
    right.tag = 2
    left.link(right)
    right.link(left)
    t.check("a cycle renders without recursing for ever",
            repr(left) == "Pair(tag: 1, peer: Pair(tag: 2, peer: Pair(...)))", repr(left))
    del left, right
    gc.collect()
    t.check("the pair is gone", sys.getrefcount(peer) == before,
            sys.getrefcount(peer) - before)
    t.check("a fresh instance still works", h.Pair().tag == 0)

    print("cycle collection in the generated file")
    t.check("the type is collectable", "voidptr(vcraft_generated__traverse_pair)" in glue)
    t.check("and can be cleared", "voidptr(vcraft_generated__clear_pair)" in glue)
    t.check("a class with no references is not", "traverse_counter" not in glue)
    t.check("the traverse reports every reference field",
            "vcraft.traverse_ref(unsafe { voidptr(&state.peer)}, visit, arg)" in glue)
    t.check("and stops on the first failure it is told about",
            "if vcraft.traverse_ref(unsafe { voidptr(&state.peer)}, visit, arg) != 0 {" in glue)
    t.check("the type object is not mistaken for an instance",
            glue.count("vcraft.is_type_object(self)") == 2,
            glue.count("vcraft.is_type_object(self)"))
    t.check("dealloc releases the references",
            "vcraft.clear_ref(unsafe { voidptr(&state.peer)})" in glue)
    t.check("a repr of a cycle is guarded", "vcraft.repr_enter(self)" in glue)
    t.check("and only for a class that can recurse", glue.count("repr_enter") == 1,
            glue.count("repr_enter"))

    print("error types")
    # Three ways for a `!T` function to name its Python exception, and they are not
    # equivalent: one is erased by V before the wrapper sees it, one travels out of band,
    # and one is set at the point of failure by a raiser the generator emitted.
    t.equal("a config line is read", h.load_config("a = 1", "a", KeyError), "1")
    t.equal("comments and blanks are skipped",
            h.load_config("# c\n\nb = two\n", "b", KeyError), "two")

    t.raises("an error type's code() names the exception", ValueError,
             "line 1: not a name=value line", lambda: h.load_config("nonsense", "a", KeyError))
    t.raises("and a builtin class can be passed in", LookupError, "no setting named zz",
             lambda: h.load_config("b = 2", "zz", KeyError))

    class Rejected(Exception):
        pass

    t.raises("a caller-defined exception class", Rejected, "no setting named zz",
             lambda: h.load_config("b = 2", "zz", Rejected))
    t.raises("through the generated raiser", Rejected, "must not be negative",
             lambda: h.checked(-1, Rejected))
    t.raises("and it can be a builtin one too", ValueError, "must not be negative",
             lambda: h.checked(-1, ValueError))
    t.equal("the same function succeeds when it can", h.checked(21, Rejected), 42)

    print("error types in the generated file")
    t.check("a raiser is emitted for the type with a class",
            "fn vcraft_generated__raise_customerror(e CustomError) IError {" in glue)
    t.check("and it raises the class the value carries",
            "vcraft.raise_custom(e.exc.ptr, e.msg())" in glue)
    t.check("a type without one gets a message-only raiser",
            "fn vcraft_generated__raise_configerror(e ConfigError) IError {" in glue)
    t.check("which says why",
            "return error(e.msg())" in glue)
    t.check("the raisers are not exported as callables",
            "vcraft_generated__raise_customerror" not in stubs)
    t.check("and neither is the error type", "class CustomError" not in stubs)
    t.check("an error type is not a class", "class CustomError" not in stubs)

    print("buffers do not copy on the way in")
    # A `[]u8` parameter takes anything bytes-like through the buffer protocol, and
    # the V slice aliases the caller's memory for exactly the call. `bytearray` and
    # `memoryview` prove it is the protocol and not the type: an exact-`bytes` check
    # would reject both.
    t.equal("bytes", h.checksum(b"hello"), 532)
    t.equal("bytearray", h.checksum(bytearray(b"hello")), 532)
    t.equal("memoryview", h.checksum(memoryview(b"hello")), 532)
    t.equal("empty", h.checksum(b""), 0)
    t.raises("str is not bytes-like", TypeError, "bytes-like",
             lambda: h.checksum("hello"))
    t.raises("int is not bytes-like", TypeError, "bytes-like",
             lambda: h.checksum(42))
    blob = bytearray(b"\x01\x02\x03\x04")
    t.equal("every byte counts", h.checksum(blob), 10)
    blob[0] = 10
    t.equal("and the caller sees its own memory", h.checksum(blob), 19)

    t.equal("a bytes return copies", h.echoed(b"abc"), b"abc")
    t.check("as immutable bytes", type(h.echoed(b"abc")) is bytes)

    print("buffers in the generated file")
    t.check("the argument is acquired",
            "vcraft.bytes_arg(args, 0, 'checksum', 'data')" in glue)
    t.check("and released on every path",
            "defer { arg0_bytes.release() }" in glue)
    t.check("the slice aliases it", "arg0_bytes.data" in glue)
    t.check("a return copies out", "vcraft.to_py_bytes_slice(result)" in glue)

    print("the GIL is released")
    # `@[vc_gil]` marks a function as pure V, and the wrapper releases the GIL around
    # the call. Four threads burning CPU each get their own core instead of queuing
    # behind one lock; on a GIL build without the release this would take four times
    # as long, and with an unbalanced release it would crash the interpreter.
    import threading
    import time

    t.equal("a nogil call computes", h.spin(100000), 639911632)
    t.raises("a nogil failure raises after re-acquiring", RuntimeError,
             "must not be negative", lambda: h.spin_checked(-1))
    t.equal("a nogil success still works", h.spin_checked(100), h.spin(100))

    seen = []
    failures = []

    def burn() -> None:
        try:
            for _ in range(3):
                seen.append(h.spin(2000000))
        except Exception as exc:  # noqa: BLE001
            failures.append(exc)

    threads = [threading.Thread(target=burn) for _ in range(4)]
    start = time.perf_counter()
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()
    elapsed = time.perf_counter() - start
    t.check("no thread failed", not failures, str(failures[:1]))
    t.check("every thread computed", len(seen) == 12 and len(set(seen)) == 1,
            f"{len(seen)} results, {len(set(seen))} distinct")
    print(f"    (four threads burned for {elapsed:.2f}s without crashing)")

    print("the release is paired in the generated file")
    t.check("the call releases", "mut saved := vcraft.allow_threads()" in glue)
    t.check("and re-acquires on the fall-through path",
            "vcraft.end_allow_threads(saved)" in glue)
    t.check("the deferred restore is guarded",
            "if saved != unsafe { nil }" in glue)
    t.check("a failure re-acquires before it raises",
            "vcraft.end_allow_threads(saved)\n\t\tsaved = unsafe { nil }\n\t\tvcraft.raise_from_error(err)"
            in glue)

    print("iterators")
    # `@[vc_iter]` runs for its side effects and the slot returns the instance;
    # `@[vc_next]` produces one item per call. The instance is its own iterator, so
    # there is no separate iterator object to get wrong.
    down = h.Countdown()
    down.start = 3
    down.current = 3
    t.equal("iterating yields each value once", list(down), [3, 2, 1])
    t.equal("the countdown is spent", list(down), [3, 2, 1])
    # Spent only until `rewind`: every `list()` calls `__iter__` first, which resets.
    # That is the documented shape of this example, not a leak: exhaustion is visible
    # through a single iterator held across calls.
    it = iter(down)
    t.check("iter() is the instance itself", it is down)
    t.equal("first item", next(it), 3)
    t.equal("second item", next(it), 2)
    t.equal("third item", next(it), 1)
    try:
        next(it)
    except StopIteration as exc:
        t.check("exhaustion raises StopIteration", True)
        t.check("with the message the V code chose", str(exc) == "no more values",
                repr(str(exc)))
    else:
        t.check("exhaustion raises StopIteration", False, "no exception")
    t.equal("and stays exhausted", list(down), [3, 2, 1])
    down.rewind()
    t.equal("rewind restores it", list(down), [3, 2, 1])

    fresh = h.Countdown()
    fresh.start = 2
    fresh.current = 2
    t.equal("a for loop consumes it", [x for x in fresh], [2, 1])
    # `tuple()` calls `__iter__` first, which rewinds: nothing here stays spent.
    t.equal("tuple() rewinds and consumes it too", tuple(fresh), (2, 1))

    print("iterators in the generated file")
    t.check("tp_iter is emitted",
            "fn vcraft_generated__iter_countdown(self voidptr) voidptr {" in glue)
    t.check("tp_iternext is emitted",
            "fn vcraft_generated__next_countdown(self voidptr) voidptr {" in glue)
    t.check("the slots are filled",
            "voidptr(vcraft_generated__iter_countdown)" in glue
            and "voidptr(vcraft_generated__next_countdown)" in glue)
    t.check("a class without the pair gets neither slot",
            "vcraft_generated__iter_counter" not in glue)
    t.check("the stub keeps both as methods",
            "    def rewind(self) -> None: ..." in stub
            and "    def advance(self) -> int: ..." in stub, stub[-600:])

    print("class stress")
    batch = [h.Counter() for _ in range(20000)]
    for item in batch:
        item.increment()
    t.check("20k instances", all(i.value == 1 for i in batch))
    del batch
    gc.collect()
    t.check("released without a leak", h.Counter().value == 0)

    print("slot ids")
    slots = subprocess.run([str(ROOT / "scripts" / "check-slot-ids.sh")],
                           capture_output=True, text=True)
    t.check("slot ids match the headers", slots.returncode == 0, slots.stdout.strip())

    print("struct mirrors")
    # The `PyModuleDef` mirror has two shapes: the GIL object header is 16 bytes
    # and the free-threaded one is 32, so `m_name` sits 16 bytes further along
    # without the GIL. The wrong shape imports on one interpreter and segfaults on
    # the other inside `PyUnicode_FromString`, with nothing pointing at the mirror,
    # so the sizes are checked here rather than trusted.
    import tempfile
    mirror_tmp = Path(tempfile.mkdtemp(prefix="vcraft-mirror-"))
    try:
        (mirror_tmp / "v.mod").write_text(
            "Module {\n\tname: 'mirrorcheck'\n\tbase_url: 'src'\n}\n")
        (mirror_tmp / "src").mkdir()
        (mirror_tmp / "src" / "main.v").write_text(
            "module main\n\nimport vcraft\n\n"
            "fn main() {\n\tunsafe { println(sizeof(vcraft.PyModuleDef)) }\n}\n")
        sizes = {}
        include = sysconfig.get_paths()["include"]
        libdir = sysconfig.get_config_var("LIBDIR") or "/usr/lib"
        # LDVERSION carries the ABI flags: `3.13t` names `libpython3.13t` on a
        # free-threaded interpreter, where `3.13` would link the wrong library.
        pylib = "python" + (sysconfig.get_config_var("LDVERSION")
                            or f"{sys.version_info[0]}.{sys.version_info[1]}")
        for label, extra in (("gil", []), ("free-threaded", ["-d", "vcraft_free_threaded"])):
            out = mirror_tmp / f"mirror-{label}"
            # Linked against libpython: the probe only prints a `sizeof`, but the
            # runtime's C file references the interpreter throughout, and an
            # executable resolves everything at link time while an extension
            # leaves it to the import.
            proc = subprocess.run(
                [str(ROOT / "scripts" / "vcraft-v.sh"),
                 "-enable-globals", "-o", str(out),
                 "-path", f"{ROOT}/vlib|@vlib",
                 "-cflags", f"-I{include}",
                 # The rpath because a libpython outside the loader's default
                 # paths (a uv or setup-python interpreter) otherwise stops the
                 # probe from starting, and it prints nothing at all.
                 "-ldflags", f"-L{libdir} -l{pylib} -Wl,-rpath,{libdir}",
                 *extra, str(mirror_tmp)],
                capture_output=True, text=True)
            t.check(f"the {label} mirror compiles", proc.returncode == 0,
                    (proc.stderr or proc.stdout).strip()[-300:])
            if proc.returncode == 0:
                probe = subprocess.run([str(out)], capture_output=True, text=True)
                t.check(f"the {label} mirror probe runs",
                        probe.returncode == 0 and probe.stdout.strip().isdigit(),
                        (probe.stderr or probe.stdout).strip()[-300:])
                if probe.returncode == 0 and probe.stdout.strip().isdigit():
                    sizes[label] = probe.stdout.strip()
        if len(sizes) == 2:
            t.check("the free-threaded header is 16 bytes wider",
                    int(sizes["free-threaded"]) - int(sizes["gil"]) == 16,
                    str(sizes))
    finally:
        import shutil
        shutil.rmtree(mirror_tmp, ignore_errors=True)

    print("layout is checked at import")
    # `check_layout` turns a drifted mirror into a named SystemError instead of a
    # wild pointer inside the interpreter. It has to run on both entry points:
    # multi-phase initialisation never runs `pyinit`'s body.
    t.check("pyinit checks the layout",
            "vcraft.check_layout() or { return unsafe { nil } }" in glue)
    t.check("exec checks the layout too",
            "vcraft.check_layout() or { return -1 }" in glue)

    print("symbol table")
    import subprocess as sp

    suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
    extension = next(iter(PYTHON_DIR.glob(f"{PACKAGE}*.so")), None)
    if extension is not None:
        out = sp.run(["nm", "-D", "--defined-only", str(extension)],
                     capture_output=True, text=True).stdout
        exported = {
            line.split()[-1]
            for line in out.splitlines()
            if len(line.split()) == 3 and line.split()[1] in ("T", "D", "B", "R", "W")
        }
        allowed = {f"PyInit_{PACKAGE}", "_v_interface_exports"}
        t.check("only PyInit is exported", exported <= allowed,
                f"extra: {sorted(exported - allowed)}")
        t.check("extension suffix", extension.name.endswith(suffix), extension.name)

    print()
    if t.failures:
        print(f"{len(t.failures)} failure(s): {', '.join(t.failures)}")
        return 1
    print(f"all {t.passed} checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
