#!/usr/bin/env python3
"""Tests for the code generator, end to end.

Builds the `examples/hello` project through `scripts/build-example.sh`, which runs
the real generator and then the real compiler, and then exercises the module it
produced. Nothing but the standard library is needed:

    ./scripts/build-example.sh hello hello_native
    python3 tests/codegen/test_codegen.py
"""

import gc
import subprocess
import sys
import sysconfig
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
PROJECT = ROOT / "examples" / "hello"
PYTHON_DIR = PROJECT / "python"
GLUE = PROJECT / "src" / "_vcraft_generated.v"
STUBS = PYTHON_DIR / "hello_native" / "_stubs.pyi"
PACKAGE = "hello_native"


class Suite:
    def __init__(self) -> None:
        self.passed = 0
        self.failures: list[str] = []

    def check(self, label: str, condition: bool, detail: str = "") -> None:
        if condition:
            self.passed += 1
            print(f"  ok   {label}")
        else:
            print(f"  FAIL {label} {detail}")
            self.failures.append(label)

    def equal(self, label: str, got, expected) -> None:
        self.check(label, got == expected, f"got {got!r}, want {expected!r}")

    def raises(self, label: str, exc_type, needle: str, call) -> None:
        try:
            result = call()
        except exc_type as exc:
            self.check(label, needle in str(exc), f"got {exc!r}")
        except Exception as exc:  # noqa: BLE001
            self.check(label, False, f"raised {type(exc).__name__}: {exc}")
        else:
            self.check(label, False, f"returned {result!r}, no exception")


def build() -> None:
    print("building the example")
    result = subprocess.run(
        [str(ROOT / "scripts" / "build-example.sh"), "hello", PACKAGE],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(result.stdout[-3000:])
        print(result.stderr[-3000:])
        raise SystemExit("build failed")


def main() -> int:
    build()
    t = Suite()

    print("generated files")
    t.check("glue written", GLUE.exists())
    t.check("stub written", STUBS.exists())
    glue = GLUE.read_text() if GLUE.exists() else ""
    t.check("glue is marked generated", "Code generated by vcraft" in glue)
    t.check("glue exports PyInit", "@[export: 'PyInit_hello_native']" in glue)
    t.check("glue is in the user module", "module hello_native" in glue)
    t.check("every annotated function is wrapped",
            glue.count("add_function_owned") == 9,
            f"found {glue.count('add_function_owned')}")

    print("annotations")
    t.check("vc_fn is exported", "'add', voidptr(vcraft_generated__wrap_add)" in glue)
    t.check("vc_raw keeps the signature", "arg0 := vcraft.from_py_voidptr(" in glue)
    t.check("no namespace annotations remain", "@[vc." not in glue)

    print("result handling")
    t.check("plain result is assigned", "result = add(arg0, arg1)" in glue)
    t.check("!T result uses error propagation",
            "vcraft.raise_from_error(err)" in glue)
    t.check("void result returns None", "vcraft.to_py_none().ptr" in glue)
    t.check("panic guard is inlined", "if message := recover()" in glue)
    t.check("guard message is escaped", "panic in V code: \\${message}" in glue
            or "panic in V code: ${message}" in glue)

    print("docstrings and signatures")
    t.check("module docstring is a literal",
            "vcraft.new_module('hello_native', '" in glue)
    t.check("signature text emitted", "'add(a: int, b: int) -> int'" in glue)
    t.check("void signature says None", "'noop() -> None'" in glue)
    stubs = STUBS.read_text() if STUBS.exists() else ""
    t.check("stub has add", "def add(a: int, b: int) -> int: ..." in stubs)
    t.check("stub has the docstring", "Adds two integers" in stubs)
    t.check("stub types the sequence", "values: Sequence[Any]" in stubs)

    print("module behaviour")
    sys.path.insert(0, str(PYTHON_DIR))
    import hello_native as h

    t.check("module docstring", "Adds two integers" in (h.__doc__ or ""))
    t.equal("add", h.add(2, 3), 5)
    t.equal("add negative", h.add(-4, 4), 0)
    t.equal("greet", h.greet("world"), "Hello, world!")
    t.equal("divide", h.divide(7.0, 2.0), 3.5)
    t.equal("repeat", h.repeat("ab", 3), "ababab")
    t.check("noop returns None", h.noop() is None)
    t.equal("total over a list", h.total([1, 2, 3, 4]), 10)
    t.equal("total over a tuple", h.total((5, 5)), 10)
    t.equal("total of empty", h.total([]), 0)
    t.equal("text signature", h.add.__doc__, "add(a: int, b: int) -> int")

    print("raw escape hatch")
    sentinel = [1, 2, 3]
    t.check("raw returns the same object", h.passthrough(sentinel) is sentinel)
    t.check("raw survives the call", h.passthrough(sentinel) == sentinel)

    print("errors")
    t.raises("V error", RuntimeError, "name must not be empty", lambda: h.greet(""))
    # `divide` names ZeroDivisionError rather than letting it fall back to
    # RuntimeError, so `except ZeroDivisionError` around a call into V keeps working.
    t.raises("V error from a float function", ZeroDivisionError, "division by zero",
             lambda: h.divide(1.0, 0.0))
    t.raises("too few arguments", TypeError, "takes 2 positional",
             lambda: h.add(1))
    t.raises("too many arguments", TypeError, "takes at most", lambda: h.add(1, 2, 3))
    t.raises("wrong argument type", TypeError, "expected int", lambda: h.add("x", 1))
    t.raises("bool is not an int", TypeError, "expected int", lambda: h.add(True, 1))
    t.raises("wrong string type", TypeError, "expected str", lambda: h.greet(5))
    t.raises("sequence expected", TypeError, "expected a sequence",
             lambda: h.total("ab"))
    t.raises("element type checked", TypeError, "expected int", lambda: h.total([1, "x"]))
    t.raises("integer overflow", OverflowError, "out of range", lambda: h.add(2**64, 1))

    print("still alive after all of that")
    t.equal("arithmetic", h.add(20, 22), 42)
    t.equal("strings", h.repeat("-", 3), "---")

    print("errors")
    t.equal("result value", h.divide(10.0, 4.0), 2.5)
    t.raises("domain error maps to its own type", ZeroDivisionError,
             "division by zero", lambda: h.divide(1.0, 0.0))
    t.equal("parse_int", h.parse_int("1234"), 1234)
    t.raises("value error", ValueError, "invalid literal",
             lambda: h.parse_int("12a4"))
    t.raises("overflow error", OverflowError, "too large",
             lambda: h.parse_int("9" * 25))
    t.raises("an anonymous error stays a RuntimeError", RuntimeError,
             "name must not be empty", lambda: h.greet(""))
    t.raises("argument type error", TypeError, "expected str",
             lambda: h.greet(123))
    t.raises("arity error", TypeError, "positional argument",
             lambda: h.add(1))

    print("panics")
    t.check("a recovered panic raises", True)
    try:
        h.first_char("")
    except RuntimeError as exc:
        t.check("panic message names the cause", "out of bounds" in str(exc), str(exc))
        t.check("panic names the V frame", "panic in V code" in str(exc), str(exc))
    else:
        t.check("a recovered panic raises", False, "no exception")
    # The point of recovering: the interpreter is still usable afterwards, and the
    # extension is not left with a half-written result or a stale exception.
    t.equal("interpreter survives", h.add(2, 3), 5)
    t.equal("extension still works", h.parse_int("7"), 7)
    t.equal("no panic state leaks", h.greet("Ana"), "Hello, Ana!")

    print("class")
    counter = h.Counter()
    t.check("instance repr", repr(counter) == "Counter(value: 0, step: 1)", repr(counter))
    t.check("class name", h.Counter.__name__ == "Counter", h.Counter.__name__)
    t.check("qualified name", h.Counter.__qualname__ == "Counter", h.Counter.__qualname__)
    t.check("module", h.Counter.__module__ == "hello_native", h.Counter.__module__)
    t.check("default field", counter.value == 0, counter.value)
    # Each call is bound before the check, because passing the call itself as the
    # failure detail would run it twice and move the number being asserted.
    first = counter.increment()
    t.check("no-arg method", first == 1, first)
    second = counter.increment()
    t.check("method mutates state", second == 2, second)
    counter.double()
    t.check("second no-arg method", counter.value == 4, counter.value)
    t.check("property reads", counter.is_zero is False, counter.is_zero)
    counter.value = 100
    t.check("field is writable", counter.value == 100, counter.value)
    counter.set_step(4)
    stepped = counter.increment()
    t.check("method with one argument", stepped == 104, stepped)
    t.check("class attributes", sorted(
        n for n in dir(h.Counter) if not n.startswith("_")) ==
        ["double", "increment", "is_zero", "set_step", "step", "value"])
    t.check("instances are distinct",
            h.Counter().value == 0 and h.Counter().value == 0)
    t.check("isinstance", isinstance(counter, h.Counter))
    t.check("subclassable", issubclass(h.Counter, object))
    t.raises("constructor takes no arguments", TypeError, "takes no arguments",
             lambda: h.Counter(1))
    t.raises("setter rejects a wrong type", TypeError, "expected int",
             lambda: setattr(counter, "value", "nope"))
    t.raises("fields cannot be deleted", AttributeError, "cannot be deleted",
             lambda: delattr(counter, "value"))
    t.check("rejected assignment changes nothing", counter.value == 104, counter.value)

    print("class docstrings")
    t.check("class docstring", h.Counter.__doc__.startswith("A counter with state."),
            h.Counter.__doc__)
    t.check("method docstring",
            h.Counter.increment.__doc__ == "increment adds step to value and returns the new total.",
            h.Counter.increment.__doc__)
    t.check("property docstring",
            h.Counter.is_zero.__doc__ == "is_zero reports whether the value is still zero.",
            h.Counter.is_zero.__doc__)
    t.check("field docstring", h.Counter.value.__doc__ == "value is the running total.",
            h.Counter.value.__doc__)

    print("class stub")
    stub = STUBS.read_text() if STUBS.exists() else ""
    t.check("class is declared", "class Counter:" in stub)
    t.check("fields are attributes", "    value: int" in stub, stub[-400:])
    t.check("methods are declared", "    def increment(self) -> int: ..." in stub)
    t.check("property is decorated", "    @property\n" in stub)
    t.check("class docstring reaches the stub", "A counter with state." in stub)

    print("class stress")
    batch = [h.Counter() for _ in range(20000)]
    for item in batch:
        item.increment()
    t.check("20k instances", all(i.value == 1 for i in batch))
    del batch
    gc.collect()
    t.check("released without a leak", h.Counter().value == 0)

    print("slot ids")
    slots = subprocess.run([str(ROOT / "scripts" / "check-slot-ids.sh")],
                           capture_output=True, text=True)
    t.check("slot ids match the headers", slots.returncode == 0, slots.stdout.strip())

    print("symbol table")
    import subprocess as sp

    suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
    extension = next(iter(PYTHON_DIR.glob(f"{PACKAGE}*.so")), None)
    if extension is not None:
        out = sp.run(["nm", "-D", "--defined-only", str(extension)],
                     capture_output=True, text=True).stdout
        exported = {
            line.split()[-1]
            for line in out.splitlines()
            if len(line.split()) == 3 and line.split()[1] in ("T", "D", "B", "R", "W")
        }
        allowed = {f"PyInit_{PACKAGE}", "_v_interface_exports"}
        t.check("only PyInit is exported", exported <= allowed,
                f"extra: {sorted(exported - allowed)}")
        t.check("extension suffix", extension.name.endswith(suffix), extension.name)

    print()
    if t.failures:
        print(f"{len(t.failures)} failure(s): {', '.join(t.failures)}")
        return 1
    print(f"all {t.passed} checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
