module vcraft_ci

import vcraft_project

// Generating a GitHub Actions workflow.
//
// The workflow is emitted rather than shipped as a template with holes in it, for the
// same reason the PEP 517 backend is: a project that copies a template has a copy, and
// the copy says nothing about which version of the tool wrote it. Emitting it from the
// binary means `vcraft generate-ci` always produces a workflow for the vcraft that ran
// it.
//
// The matrix is the interesting part and the part that is easy to get wrong. A wheel is
// per-interpreter, per-ABI and per-platform, and a workflow that builds one of them
// tests one. The matrix below covers the combinations a release actually needs and
// skips the ones that cannot work.

// Target is one cell of the build matrix.
pub struct Target {
pub mut:
	// os is the runner image: ubuntu, ubuntu-latest or macos.
	os string
	// python is the interpreter version, or empty for the runner's default.
	python string
	// abi3, when set, builds against the stable ABI from that version on.
	abi3 string
	// free_threading builds a free-threaded extension.
	free_threading bool
	// target is the wheel's platform tag, when the runner does not produce it by
	// itself.
	target string
	// note explains why a cell exists, and becomes a workflow comment.
	note string
}

// workflow renders the workflow file.
//
// `vcraft_action` is the action the build step uses. It defaults to `vcraft-action@v1`
// because that is the published action a consumer expects; a project pinned to its own
// build can name a different ref.
pub fn workflow(p vcraft_project.Project, vcraft_action string, free_threading bool) string {
	mut w := new_builder()
	w.write_string(generated_header(p))
	w.write_string('name: build\n\n')
	w.write_string('on:\n')
	w.write_string('  push:\n')
	w.write_string('    branches: [main]\n')
	w.write_string('  pull_request:\n')
	w.write_string('  workflow_dispatch:\n\n')
	w.write_string('jobs:\n')
	w.write_string('  build:\n')
	w.write_string('    name: ' + gha('matrix.target') + ' on ' + gha('matrix.os') + '\n')
	w.write_string('    runs-on: ' + gha('matrix.os') + '\n')
	w.write_string('    strategy:\n')
	w.write_string('      fail-fast: false\n')
	w.write_string('      matrix:\n')
	w.write_string('        include:\n')
	for t in targets(p, free_threading) {
		w.write_string('          - target: ' + quote(t.target) + '\n')
		w.write_string('            os: ' + quote(t.os) + '\n')
		if t.python.len > 0 {
			w.write_string('            python: ' + quote(t.python) + '\n')
		}
		if t.abi3.len > 0 {
			w.write_string('            abi3: ' + quote(t.abi3) + '\n')
		}
		if t.free_threading {
			w.write_string('            free-threading: true\n')
		}
	}
	w.write_string('\n    steps:\n')
	w.write_string('      - uses: actions/checkout@v4\n\n')
	w.write_string('      - name: set up Python\n')
	w.write_string('        uses: actions/setup-python@v5\n')
	w.write_string('        with:\n')
	w.write_string('          python-version: ' + gha('matrix.python') + '\n\n')
	w.write_string('      - name: install vcraft\n')
	w.write_string('        run: pip install vcraft\n\n')
	w.write_string('      - name: build\n')
	w.write_string('        uses: ' + vcraft_action + '\n')
	w.write_string('        with:\n')
	w.write_string('          abi3: ' + gha('matrix.abi3') + '\n')
	w.write_string('          free-threading: ' + gha('matrix.free-threading') + '\n\n')
	w.write_string('      - name: upload\n')
	w.write_string('        uses: actions/upload-artifact@v4\n')
	w.write_string('        with:\n')
	w.write_string('          name: ' + gha('matrix.target') + '\n')
	w.write_string('          path: dist/*.whl\n\n')
	w.write_string('      - name: test\n')
	w.write_string('        run: |\n')
	w.write_string('          python -m venv /tmp/check\n')
	w.write_string('          /tmp/check/bin/pip install dist/*.whl\n')
	w.write_string('          /tmp/check/bin/python -c "import ${p.module}; print(${p.module}.__name__)"\n')
	return w.str()
}

// generated_header is the comment at the top of the file.
//
// It names the distribution and the version of vcraft that wrote it, so that a
// workflow found in a repository says which tool produced it rather than looking like
// something a person wrote.
fn generated_header(p vcraft_project.Project) string {
	return '# Generated by vcraft ' + vcraft_project.version + ' for ' + p.name + '.\n' +
		'# Regenerate with `vcraft generate-ci`. Do not edit by hand: the matrix is\n' +
		'# derived from what this version of vcraft supports, and a hand-edited matrix\n' +
		'# stops matching the tag logic in the binary.\n\n'
}

// targets returns the matrix cells.
//
// The cells are the ones that produce a wheel somebody can install. Two combinations
// that look plausible are deliberately absent: an abi3 build and a free-threaded build
// are mutually exclusive, because the free-threaded runtime has no stable ABI; and
// there is no macOS arm64 cell paired with macOS x86_64, because a universal2 wheel is
// built once on one of them rather than twice.
pub fn targets(p vcraft_project.Project, free_threading bool) []Target {
	mut out := []Target{}
	if free_threading {
		// A free-threaded build has no stable ABI, so the matrix is one cell per
		// platform and each names its own interpreter rather than a version the runner
		// might provide with the GIL.
		out << Target{
			os:             'ubuntu-latest'
			target:         'cp3.13t-cp313t-manylinux-x86_64'
			free_threading: true
			note:           'the free-threaded build has no stable ABI'
		}
		out << Target{
			os:             'macos-14'
			target:         'cp3.13t-cp313t-macosx-arm64'
			free_threading: true
		}
		return out
	}
	if p.abi3.len > 0 {
		// One wheel covers every interpreter from the floor up, so one cell per
		// platform is the whole matrix.
		out << Target{
			os:     'ubuntu-latest'
			python: p.abi3
			abi3:   p.abi3
			target: 'cp' + compact(p.abi3) + '-abi3-manylinux-x86_64'
			note:   'one wheel covers every interpreter from the floor up'
		}
		out << Target{
			os:     'ubuntu-latest'
			python: p.abi3
			abi3:   p.abi3
			target: 'cp' + compact(p.abi3) + '-abi3-manylinux-aarch64'
		}
		out << Target{
			os:     'macos-14'
			python: p.abi3
			abi3:   p.abi3
			target: 'cp' + compact(p.abi3) + '-abi3-macosx-universal2'
		}
		out << Target{
			os:     'windows-latest'
			python: p.abi3
			abi3:   p.abi3
			target: 'cp' + compact(p.abi3) + '-abi3-win_amd64'
		}
		return out
	}
	// Without abi3 every interpreter needs its own wheel, so the matrix is
	// interpreters crossed with the platforms that have a current interpreter.
	for version in ['3.12', '3.13', '3.14'] {
		out << Target{
			os:     'ubuntu-latest'
			python: version
			target: 'cp' + compact(version) + '-manylinux-x86_64'
		}
		out << Target{
			os:     'macos-14'
			python: version
			target: 'cp' + compact(version) + '-macosx-universal2'
		}
	}
	return out
}

// compact turns `3.12` into `312`, which is how a tag spells it.
fn compact(version string) string {
	return version.replace('.', '')
}

// gha renders a GitHub Actions expression.
//
// The `${{ }}` syntax is the same shape as a V interpolation, and V tries to evaluate
// it: `${{ matrix.python }}` becomes an attempt to interpolate a field of a struct
// named `matrix`, which does not exist. The dollar and braces are therefore written as
// separate pieces, so the literal reaches the file and nothing is evaluated here.
fn gha(expression string) string {
	return '$' + '{' + expression + '}'
}

// quote renders a YAML scalar.
//
// Quoted throughout, because a bare `3.10` in YAML is a float and comes back as `3.1`,
// which is a version nobody publishes. The value is interpolated at the call site by
// the builder, so this takes the finished text.
fn quote(text string) string {
	return '"' + text + '"'
}

// new_builder is a tiny string accumulator.
//
// Not `strings.Builder`: that is a standard-library type whose methods this module would
// have to import, and a workflow is written once.
struct Builder {
mut:
	out string
}

fn new_builder() &Builder {
	return &Builder{}
}

fn (mut b Builder) write_string(text string) {
	b.out += text
}

fn (b &Builder) str() string {
	return b.out
}
