module vcraft_codegen

// Emitting the glue.
//
// The output is a V file in the user's own module, so the trampolines call their
// functions directly with no module prefix and no cross-module edge. It is
// ordinary V that a person can read and a person can debug.
//
// The shape of a trampoline is fixed. For a plain function:
//
//	fn vcraft_generated__wrap_add(self voidptr, args voidptr, nargs isize) voidptr {
//		if nargs != 2 { vcraft.wrong_nargs('add', 2, int(nargs)) return unsafe { nil } }
//		arg0 := vcraft.from_py_int_arg(args, 0, 'add', 'a') or { return unsafe { nil } }
//		arg1 := vcraft.from_py_int_arg(args, 1, 'add', 'b') or { return unsafe { nil } }
//		mut result := 0
//		defer { if message := recover() { vcraft.raise_runtime_error('panic in V code: ${message}') } }
//		result = add(arg0, arg1)
//		if vcraft.error_is_set() { return unsafe { nil } }
//		return vcraft.to_py_int(result).ptr
//	}
//
// The `defer` is what keeps a V panic, which calls exit(1), from taking the
// interpreter down. When one fires, `result` keeps its zero value and the
// `error_is_set` check turns that into a Python exception rather than a bogus
// value. Nothing the guard touches needs to survive the jump, because the
// exception state it sets lives on the C side.

import strings

// new_builder returns an empty builder.
//
// V's `strings.Builder.new()` returns the zero value rather than a value, so a
// one-line wrapper is clearer at the many call sites below than the cast is.
fn new_builder() strings.Builder {
	return strings.Builder{}
}

const generated_header = '// Code generated by vcraft. Do not edit.\n' +
	'// Regenerate with `vcraft build`; it is written to disk and overwritten.\n\n'

// emit_glue renders the glue file for a project.
pub fn emit_glue(p Project) string {
	mut w := new_builder()
	w.write_string(generated_header)
	w.write_string('module ${p.module}\n\n')
	w.write_string('import vcraft\n\n')
	w.write_string(glue_module_body(p))
	for f in p.funcs {
		w.write_string('\n')
		w.write_string(emit_trampoline(f))
	}
	for e in p.errors {
		w.write_string('\n')
		w.write_string(emit_error_raiser(e))
	}
	for c in p.classes {
		w.write_string(emit_class(p, c))
		for m in c.methods {
			// `@[vc_eq]` and `@[vc_hash]` fill the type's slots rather than the method
			// table, and they are called from `richcompare` and `hash` rather than from
			// Python. Emitting them as methods would put a `state.(arg0, arg1)` in the
			// generated source, because two receivers are not a receiver plus arguments.
			if m.eq || m.hash {
				continue
			}
			w.write_string('\n')
			if m.property {
				w.write_string(emit_property_trampoline(p, c, m))
			} else {
				w.write_string(emit_method_trampoline(p, c, m))
			}
		}
	}
	return w.str()
}

// glue_module_body renders the module definition and the two entry points.
//
// The tables the type needs are module-level globals rather than locals, because
// CPython keeps reading them: `PyType_FromSpec` copies what it needs, but a
// PyMethodDef's name and doc pointers are borrowed for the life of the type.
//
// The module under construction is a global rather than a local of `pyinit`.
//
// Single-phase initialisation lets `pyinit` build a module and return it: CPython calls
// `PyInit_` once and is done. Multi-phase initialisation, which an abi3 build has to
// use, does not: `PyInit_` returns a module *definition*, the interpreter then calls the
// `Py_mod_exec` slot inside it, and the definition must still be alive at that point. A
// local in `pyinit` is a dangling pointer by then, and the interpreter reads it as a
// module and crashes with nothing in the generated source to explain it.
//
// So `pyinit` is a thin wrapper that builds into the global and returns whatever this
// build's API expects, and `exec` does the part that fills the module in. `pyinit` calls
// `exec` itself on a single-phase build, so there is one copy of that code rather than
// two that can disagree.
pub fn glue_module_body(p Project) string {
	mut w := new_builder()
	w.write_string('__global (\n')
	w.write_string("\tg_vc_module = vcraft.new_module('${p.package}', " +
		'${vstring_literal(module_docstring(p))})\n')
	// The type handles are globals because the comparison and hash slots reference them
	// and CPython calls those after `Py_mod_exec` has returned.
	for c in p.classes {
		// `mut x = ...` is not valid in a global block: V's global syntax wants the
		// mutability and the value in separate places, and a `mut` here is rejected with
		// "unexpected token `=`, expecting name".
		w.write_string('\t' + c.ctype + ' = vcraft.PyObj{}\n')
	}
	// The base tuple is a global because `PyType_FromSpec` borrows the tuple for the
	// duration of its call and the type keeps a reference to the base types afterwards. A
	// local would be freed before the interpreter could subclass anything.
	for c in p.classes {
		if c.base_index < 0 {
			continue
		}
		w.write_string('\tg_vc_bases_' + c.key + ' = vcraft.PyObj{}\n')
	}
	w.write_string(')\n\n')
	w.write_string("@[export: 'PyInit_${p.package}']\n")
	w.write_string('fn vcraft_generated__pyinit() voidptr {\n')
	// The mirrors of CPython's structs are checked before anything is built with
	// them. A drifted mirror reads and writes at the wrong offsets, and every later
	// symptom is a wild pointer inside the interpreter -- un-diagnosable -- while
	// this names the struct. The free-threaded object header is the case that
	// motivated it: the wrong `PyModuleDef` mirror segfaults in `PyUnicode_FromString`
	// on import with nothing pointing at the mirror.
	w.write_string('\tvcraft.check_layout() or { return unsafe { nil } }\n')
	// The `for` is emitted once and the body once per function. Writing the header
	// inside the generator's loop instead produces one `for` per function, all of them
	// nested, and the generated file does not compile.
	//
	// The loop variable is `fn_` rather than `f` because the generated loops share a
	// file with the generator's own, and V rejects a redefinition of an iteration
	// variable in the same scope.
	//
	// The header is written once and the body once per function. The signature differs
	// per function, so it cannot be hoisted out of the loop; the header can, and
	// writing it inside the generator's loop instead produces one `for` per function,
	// all of them nested, which does not compile.
	// One call per function, and the loop variable inside the generated source is
	// `fn_` because the generated loops share a file with the generator's own and V
	// rejects a redefinition of an iteration variable in the same scope.
	for f in p.funcs {
		flags := if f.params.len == 0 { 'vcraft.meth_noargs' } else {
			'vcraft.meth_fastcall'
		}
		w.write_string('\tg_vc_module.add_function_owned(' + vstring_literal(f.name) +
			', voidptr(' + f.trampoline + '), ' + flags + ',\n')
		w.write_string('\t\t${vstring_literal(python_signature(f))})\n')
	}
	w.write_string('\tg_vc_module.set_exec(voidptr(vcraft_generated__exec))\n')
	w.write_string('\tmodule := g_vc_module.seal()\n')
	w.write_string('\treturn module.ptr\n}\n\n')
	w.write_string('// vcraft_generated__exec populates the module.\n')
	w.write_string('//\n')
	w.write_string("// CPython calls this through the `Py_mod_exec` slot on an abi3 build, and\n")
	w.write_string('// `pyinit` calls it directly otherwise, so the same code fills the module in\n')
	w.write_string('// either way.\n')
	w.write_string('fn vcraft_generated__exec(module voidptr) int {\n')
	// Checked here as well as in `pyinit`: multi-phase initialisation never runs
	// `pyinit`'s body, so without this an abi3 build would skip the check entirely.
	w.write_string('\tvcraft.check_layout() or { return -1 }\n')
	// The state chain lives in thread-local storage, keyed once here. `exec` runs once
	// per import under the import lock on every path -- single-phase through `pyinit`,
	// multi-phase through the interpreter -- so by the time any trampoline runs, on any
	// thread, the key exists.
	w.write_string('\tvcraft.init_state()\n')
	// The method table has to be installed here rather than left to module creation:
	// under multi-phase initialisation the module arrives empty.
	//
	// The types are declared here rather than where they are created because the
	// comparison and hash slots need to name them and CPython calls those after `exec`
	// has returned. A local would be out of scope, and the generated file would not
	// compile at all -- which is a better failure than a type whose `__eq__` silently
	// compares identity because the slot was never filled.
	w.write_string('\tg_vc_module.install_functions(module) or { return -1 }\n')
	for c in p.classes {
		w.write_string(render_class_exec(p, c))
	}
	w.write_string('\t_ = module\n')
	w.write_string('\treturn 0\n}\n')
	return w.str()
}

// pyinterp renders a `${name}` the way it must appear in generated V source.
//
// V has no spelling for a literal `${` inside a double-quoted string, so a generator
// that emits interpolated code cannot write one directly. Splitting the string around
// the interpolation is the way out: the pieces are plain text and only the middle is
// this generator's own substitution.
// interp renders a `${name}` as it must appear in generated V source.
//
// V has no spelling for a literal `${` inside a double-quoted string, so a generator
// that emits interpolated code cannot write one directly: unescaped, V tries to
// interpolate the name here, where it is not in scope. Splitting the literal into the
// pieces around the interpolation is the way out — `'${'` and `'}'` are ordinary text.
pub fn interp(name string) string {
	// The dollar is written as a byte rather than as `${`, because a `${` inside a
	// double-quoted V string is an interpolation and V tries to evaluate it here.
	return '$' + '{' + name + '}'
}

// render_class_exec renders a class's registration for inside `exec`.
pub fn render_class_exec(p Project, c Class) string {
	// Rendered at generation time rather than as a `for` in the output: every value
	// here is known now, and a generated `for` over the classes would need its own
	// interpolation trick for no benefit.
	mut w := new_builder()
	if c.base_index >= 0 {
		// Filled here rather than in the global's initialiser, because the base type is
		// created earlier in this same function and a global initialiser would run before
		// it exists.
		w.write_string('\tg_vc_bases_' + c.key + ' = vcraft.tuple_of_one(' +
			p.classes[c.base_index].ctype + ')\n')
	}
	w.write_string('\t' + c.ctype + ' = vcraft.new_type(')
	w.write_string(vstring_literal(c.qualified) + ',\n')
	w.write_string('\t\t' + vstring_literal(c.doc) + ',\n')
	w.write_string('\t\tvoidptr(' + c.ctor + '),\n')
	// `tp_init` is left null: the constructor runs in `tp_new`, so a subclass that
	// overrides `__init__` still gets a chance to add to it.
	w.write_string('\t\tunsafe { nil },\n')
	w.write_string('\t\tvoidptr(' + c.dealloc + '),\n')
	// Taking the address of a mutable array element needs an unsafe block, and both
	// tables are module-level globals that the type borrows for its lifetime.
	if c.methods.any(it.property == false) {
		w.write_string('\t\tunsafe { voidptr(&g_vc_methods_' + c.key + '[0]) },\n')
	} else {
		w.write_string('\t\tunsafe { nil },\n')
	}
	if c.fields.len > 0 || c.methods.any(it.property) {
		w.write_string('\t\tunsafe { voidptr(&g_vc_getsets_' + c.key + '[0]) },\n')
	} else {
		w.write_string('\t\tunsafe { nil },\n')
	}
	w.write_string('\t\tvoidptr(' + c.repr + '),\n')
	w.write_string('\t\tvoidptr(' + c.richcompare + '),\n')
	w.write_string('\t\tvoidptr(' + c.hash_fn + '),\n')
	if c.base_index < 0 {
		w.write_string('\t\tunsafe { nil },\n')
	} else {
		w.write_string('\t\tvoidptr(g_vc_bases_' + c.key + '.ptr),\n')
	}
	// `tp_traverse` and `tp_clear`, only for a class that holds references. `new_type`
	// turns them into `Py_TPFLAGS_HAVE_GC`, and that flag is what makes the collector
	// look at the instances at all: without it a cycle is never found, and the objects
	// in it are never freed.
	if c.ref_fields().len > 0 {
		w.write_string('\t\tvoidptr(vcraft_generated__traverse_' + c.key + '),\n')
		w.write_string('\t\tvoidptr(vcraft_generated__clear_' + c.key + '),\n')
	} else {
		w.write_string('\t\tunsafe { nil },\n')
		w.write_string('\t\tunsafe { nil },\n')
	}
	// `tp_iter` and `tp_iternext`, only for a class that declares the pair. The slots
	// are what make `iter()` and `next()` work; without them the methods are ordinary
	// attributes that happen to be named `iter` and `next`.
	if c.iter_fn.len > 0 {
		w.write_string('\t\tvoidptr(' + c.iter_fn + '),\n')
		w.write_string('\t\tvoidptr(' + c.next_fn + '),\n')
	} else {
		w.write_string('\t\tunsafe { nil },\n')
		w.write_string('\t\tunsafe { nil },\n')
	}
	w.write_string('\t)\n')
	// The error check is here rather than inside `new_type` because a class that fails
	// to build is a generator-level problem: the interpreter reports "raised
	// unreported exception" and nothing else, so the reason has to be surfaced while
	// there is still a name to attach it to.
	w.write_string('\tif vcraft.error_is_set() {\n')
	w.write_string('\t\teprintln(' + vstring_literal('vcraft: cannot create the type ' +
		c.name) + ')\n')
	w.write_string('\t\treturn -1\n')
	w.write_string('\t}\n')
	w.write_string('\tvcraft.add_object_ref_on(module, ' + vstring_literal(c.name) + ', ' +
		c.ctype + ')\n')
	return w.str()
}

// emit_error_raiser renders the raiser for one `@[vc_error]` type.
//
// V erases an error to `IError` by the time a wrapper sees it, so nothing but the message
// survives the trip out of a `!T` function. The exception class therefore has to be set
// *before* the value is returned, and this is the function that does it: it takes the
// user's own value, sets the pending Python exception from it, and hands back an error
// carrying the same message.
//
//	// generated
//	pub fn vcraft_generated__raise_configerror(e ConfigError) IError {
//		return vcraft.raise_custom(e.exc.ptr, e.msg())
//	}
//
// so the V side reads:
//
//	if !ok {
//		return vcraft_generated__raise_configerror(ConfigError{
//			exc: vcraft.borrow(class_ptr),
//			detail: 'no such section',
//		})
//	}
//
// A type with no `PyObj` field gets a raiser that names a builtin exception from the
// `code()` it already has, which `raise_from_error` reads on the far side:
//
//	pub fn vcraft_generated__raise_configerror(e ConfigError) IError {
//		return error(e.msg())
//	}
//
// and needs nothing at all from the generator to work: any struct with `msg()` and
// `code()` reaches Python as whatever `code()` names. The raiser exists for the type whose
// exception is not one of the builtin ones.
fn emit_error_raiser(e ErrorType) string {
	mut w := new_builder()
	w.write_string('// ---- ${e.name}\n\n')
	w.write_string('// ${e.name} is a V error type, so it can be returned from a `!T` function.\n')
	if e.doc.len > 0 {
		w.write_string('//\n')
		for line in e.doc.split('\n') {
			w.write_string('// ' + line.trim_right(' \t') + '\n')
		}
	}
	w.write_string('fn ${e.raiser}(e ${e.name}) IError {\n')
	if e.exc_field.len > 0 {
		// The exception class is borrowed from the value and CPython keeps its own
		// reference on the exception it builds, so nothing is released here.
		w.write_string('\treturn vcraft.raise_custom(e.${e.exc_field}.ptr, e.msg())\n')
	} else {
		w.write_string('\t// No `PyObj` field, so this type names a builtin exception from\n')
		w.write_string('\t// `code()` and the raiser only has to carry the message.\n')
		w.write_string('\treturn error(e.msg())\n')
	}
	w.write_string('}\n\n')
	return w.str()
}

// emit_nogil_open renders the GIL release and its guards for a `@[vc_gil]` call.
//
// The release is paired in a `defer` rather than only on the fall-through path, because
// a panic unwinds past the explicit release. The `saved != nil` guard is what keeps that
// from double-restoring: the fall-through path restores and nulls the handle, so the
// deferred restore on the way out finds nothing to do, while a panic unwinds straight
// into a restore of the handle that is still set.
//
// The `recover` defer is registered *before* the restore defer. Defers run last in,
// first out, so the restore runs first on a panic and the raise that follows it already
// holds the GIL. Registered the other way round, the raise would run without it.
fn emit_nogil_open() string {
	mut w := new_builder()
	w.write_string('\tmut saved := vcraft.allow_threads()\n')
	w.write_string('\tdefer {\n')
	w.write_string("\t\tif message := recover() {\n")
	w.write_string("\t\t\tvcraft.raise_runtime_error('panic in V code: \${message}')\n")
	w.write_string('\t\t}\n')
	w.write_string('\t}\n')
	w.write_string('\tdefer {\n')
	w.write_string('\t\tif saved != unsafe { nil } {\n')
	w.write_string('\t\t\tvcraft.end_allow_threads(saved)\n')
	w.write_string('\t\t}\n')
	w.write_string('\t}\n')
	return w.str()
}

// emit_nogil_close renders the re-acquire after a `@[vc_gil]` call returns.
//
// Paired with the `nil` assignment: without it the deferred restore would fire on the
// way out and restore twice, which leaves the GIL count wrong and crashes the next
// thread switch inside CPython rather than anywhere near the call that unbalanced it.
fn emit_nogil_close() string {
	return '\tvcraft.end_allow_threads(saved)\n' + '\tsaved = unsafe { nil }\n'
}

// emit_nogil_failure renders the failure path of a `@[vc_gil]` call that returns `!T`.
//
// The error is raised here rather than captured because the GIL is re-acquired first:
// raising touches Python, and the whole point of the release is that nothing between
// the two does. The handle is nulled for the same reason as on the success path, so
// the deferred restore finds nothing to do.
fn emit_nogil_failure(inner string) string {
	return '\t\tvcraft.end_allow_threads(saved)\n' + '\t\tsaved = unsafe { nil }\n' +
		'\t\t' + inner + '\n'
}

// emit_nargs_check renders the arity check at the top of a positional trampoline.
//
// One comparison on the success path. The message, and the choice between too few
// and too many, only run when it fails. Checking before any argument is read also
// means a reader never sees an index past `nargs`.
fn emit_nargs_check(f Func) string {
	return '\tif nargs != ${f.params.len} {\n' +
		"\t\tvcraft.wrong_nargs('${f.name}', ${f.params.len}, int(nargs))\n" +
		'\t\treturn unsafe { nil }\n\t}\n'
}

// emit_method_trampoline renders a method of a class.
//
// It is the ordinary trampoline wrapped in the two statements that move the V value
// in and out of the instance's state block.
pub fn emit_method_trampoline(p Project, c Class, f Func) string {
	mut w := new_builder()
	signature := if f.params.len == 0 {
		'self voidptr, args voidptr'
	} else {
		'self voidptr, args voidptr, nargs isize'
	}
	w.write_string('fn ${f.trampoline}(${signature}) voidptr {\n')
	if f.params.len > 0 {
		w.write_string(emit_nargs_check(f))
	}
	mut names := []string{}
	for i, param in f.params {
		name := local_name(i)
		names << name
		w.write_string('\t${reader_expr(lookup(param.v_type), name, i, f.name, param.name, param.v_type)}\n')
	}
	w.write_string(emit_state_pointer(c, no_state_exit(c, 'unsafe { nil }')))
	w.write_string(emit_enter_state(p, c))
	ret := lookup(f.v_ret)
	has_value := ret != .void
	if has_value {
		w.write_string('\tmut result := ${zero_value(ret, f.v_ret)}\n')
	}
	if f.nogil {
		w.write_string(emit_nogil_open())
	} else {
		w.write_string('\tdefer {\n')
		w.write_string('\t\tif message := recover() {\n')
		w.write_string("\t\t\tvcraft.raise_runtime_error('panic in V code: \${message}')\n")
		w.write_string('\t\t}\n')
		w.write_string('\t}\n')
	}
	call := if f.params.len == 0 { 'state.' + c.self_access() + '${f.name}()' } else { 'state.' + c.self_access() + '${f.name}(${names.join(', ')})' }
	if f.returns_result {
		inner := 'vcraft.raise_from_error(err)\n\t\treturn unsafe { nil }'
		if has_value {
			// Assigned, not declared: `mut result` was emitted above when the method
			// returns a value, and `:=` here redefines it, which V rejects outright.
			if f.nogil {
				w.write_string('\tresult = ${call} or {\n' + emit_nogil_failure(inner) +
					'\t}\n')
			} else {
				w.write_string('\tresult = ${call} or {\n\t\t${inner}\n\t}\n')
			}
		} else {
			if f.nogil {
				w.write_string('\t${call} or {\n' + emit_nogil_failure(inner) + '\t}\n')
			} else {
				w.write_string('\t${call} or {\n\t\t${inner}\n\t}\n')
			}
		}
		// Re-acquired before the state is written back and the error is checked: the
		// check touches Python, and without the GIL it races the next thread switch.
		if f.nogil {
			w.write_string(emit_nogil_close())
		}
	} else if has_value {
		w.write_string('\tresult = ${call}\n')
		if f.nogil {
			w.write_string(emit_nogil_close())
		}
	} else {
		w.write_string('\t${call}\n')
		if f.nogil {
			w.write_string(emit_nogil_close())
		}
	}
	// The instance is written back before anything can fail, so a method that
	// raises leaves the object consistent.
	w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
	if has_value {
		w.write_string('\treturn ${return_expr(ret, 'result', false, f.v_ret)}\n')
	} else {
		w.write_string('\treturn vcraft.to_py_none().ptr\n')
	}
	w.write_string('}\n')
	return w.str()
}

// emit_property_trampoline renders a method exposed as a Python property.
//
// A getter is called with the instance and the descriptor closure, not with an
// argument tuple, and it must take no arguments.
pub fn emit_property_trampoline(p Project, c Class, f Func) string {
	mut w := new_builder()
	w.write_string('fn ${f.trampoline}(self voidptr, closure voidptr) voidptr {\n')
	w.write_string(emit_state_pointer(c, no_state_exit(c, 'unsafe { nil }')))
	w.write_string(emit_enter_state(p, c))
	ret := lookup(f.v_ret)
	if f.nogil {
		w.write_string(emit_nogil_open())
	} else {
		w.write_string('\tdefer {\n')
		w.write_string('\t\tif message := recover() {\n')
		w.write_string("\t\t\tvcraft.raise_runtime_error('panic in V code: \${message}')\n")
		w.write_string('\t\t}\n')
		w.write_string('\t}\n')
	}
	if ret != .void {
		// A property getter declares its own `result`. It has no argument tuple, so it
		// does not go through the path that declares one for a method, and without this
		// the return statement at the end refers to a variable that was never declared.
		w.write_string('\tmut result := ${zero_value(ret, f.v_ret)}\n')
	}
	if f.returns_result {
		inner := 'vcraft.raise_from_error(err)\n\treturn unsafe { nil }'
		// Assigned, not declared: `mut result` is emitted above when the method returns
		// a value, and `:=` here would shadow it -- or rather, redefine it, which V
		// rejects outright.
		if f.nogil {
			w.write_string('\tresult = state.' + c.self_access() +
				'${f.name}() or {\n' + emit_nogil_failure(inner) + '\t}\n')
		} else {
			w.write_string('\tresult = state.' + c.self_access() + '${f.name}() or {\n\t${inner}\n\t}\n')
		}
		if f.nogil {
			w.write_string(emit_nogil_close())
		}
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
		w.write_string('\treturn ${return_expr(ret, 'result', false, f.v_ret)}\n')
	} else if ret != .void {
		// A plain getter: the call is assigned to the `result` declared above. Without
		// this the value is computed and dropped on the floor, and the getter returns the
		// zero value it was initialised with.
		w.write_string('\tresult = state.' + c.self_access() + '${f.name}()\n')
		if f.nogil {
			w.write_string(emit_nogil_close())
		}
		w.write_string('\treturn ${return_expr(ret, 'result', false, f.v_ret)}\n')
	} else {
		// A property returning nothing has no `result` to assign: it was never declared,
		// and assigning to it is a compile error rather than a warning.
		w.write_string('\tstate.' + c.self_access() + '${f.name}()\n')
		if f.nogil {
			w.write_string(emit_nogil_close())
		}
		w.write_string('\treturn ${return_expr(ret, 'result', false, f.v_ret)}\n')
	}
	w.write_string('}\n')
	return w.str()
}

// module_docstring is the module's `__doc__`, taken from the first exported
// function's doc comment since a project has no module-level one of its own.
fn module_docstring(p Project) string {
	for f in p.funcs {
		if f.doc.len > 0 {
			return f.doc.split('\n')[0]
		}
	}
	return '${p.package}, built with vcraft.'
}

// local_name is the generated name for the i-th argument. It is positional rather
// than taken from the V parameter so that two parameters of the same type cannot
// collide, which is what a naive `v :=` per parameter would do.
fn local_name(i int) string {
	return 'arg${i}'
}

// emit_trampoline renders one trampoline.
pub fn emit_trampoline(f Func) string {
	mut w := new_builder()
	signature := if f.params.len == 0 {
		'self voidptr, args voidptr'
	} else {
		'self voidptr, args voidptr, nargs isize'
	}
	w.write_string('fn ${f.trampoline}(${signature}) voidptr {\n')

	if f.params.len > 0 {
		w.write_string(emit_nargs_check(f))
	}

	// `@[vc_raw]` keeps the declared signature but skips every conversion: each
	// parameter is handed over as the borrowed `PyObject *` itself, and the result
	// is returned as whatever pointer the function produced. The V function owns
	// every reference it touches.
	mut names := []string{}
	for i, param in f.params {
		if f.raw {
			name := local_name(i)
			names << name
			w.write_string('\t${name} := vcraft.from_py_voidptr(' +
				"vcraft.require_arg(args, ${i}, '${f.name}', '${param.name}'))\n")
			w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
			continue
		}
		strategy := lookup(param.v_type)
		name := local_name(i)
		names << name
		w.write_string('\t${reader_expr(strategy, name, i, f.name, param.name, param.v_type)}\n')
	}


	ret := lookup(f.v_ret)
	has_value := f.raw || ret != .void

	// The result is declared before the guard so that the call has somewhere to assign
	// even when the guard unwinds past it. Declared for a `!T` function too: the call
	// below assigns to it rather than introducing it with `:=`, because `:=` on an
	// existing name is a redefinition and V rejects that outright.
	if has_value {
		w.write_string('\tmut result := ${zero_value(ret, f.v_ret)}\n')
	}
	// A raw function's result is a pointer the V side already owns, so it is
	// handed back without touching the reference count.
	//
	// `@[vc_gil]` replaces the guard with the release and its own pair of guards: the
	// recover defer first so it runs last, already holding the GIL, and the restore
	// defer second so it runs first. Everything between them runs without the GIL and
	// must not touch Python.
	if f.nogil {
		w.write_string(emit_nogil_open())
	} else {
		w.write_string('\tdefer {\n')
		w.write_string('\t\tif message := recover() {\n')
		w.write_string("\t\t\tvcraft.raise_runtime_error('panic in V code: \${message}')\n")
		w.write_string('\t\t}\n')
		w.write_string('\t}\n')
	}

	call := if f.params.len == 0 { '${f.name}()' } else { '${f.name}(${names.join(', ')})' }

	if f.returns_result {
		// V has no `is` test for a Result, so error propagation is the mechanism:
		// the `or` block receives `err` directly and turns it into a Python
		// exception before returning.
		inner := 'vcraft.raise_from_error(err)\n\t\treturn unsafe { nil }'
		if has_value {
			// Assigned, not declared: `mut result` was emitted above when the method
			// returns a value, and `:=` here redefines it, which V rejects outright.
			if f.nogil {
				w.write_string('\tresult = ${call} or {\n' + emit_nogil_failure(inner) +
					'\t}\n')
			} else {
				w.write_string('\tresult = ${call} or {\n\t\t${inner}\n\t}\n')
			}
		} else {
			if f.nogil {
				w.write_string('\t${call} or {\n' + emit_nogil_failure(inner) + '\t}\n')
			} else {
				w.write_string('\t${call} or {\n\t\t${inner}\n\t}\n')
			}
		}
		// The success path re-acquires here rather than in the deferred restore: everything
		// below touches Python (`error_is_set`, boxing the result), and running any of it
		// without the GIL races the next thread switch and dies inside `PyErr_Occurred`
		// with nothing in the frame pointing back at the missing re-acquire.
		if f.nogil {
			w.write_string(emit_nogil_close())
		}
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
	} else {
		if has_value {
			w.write_string('\tresult = ${call}\n')
		} else {
			w.write_string('\t${call}\n')
		}
		if f.nogil {
			w.write_string(emit_nogil_close())
		}
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
		if has_value {
			w.write_string('\treturn ${return_expr(ret, 'result', f.raw, f.v_ret)}\n')
		} else {
			w.write_string('\treturn vcraft.to_py_none().ptr\n')
		}
		w.write_string('}\n')
		return w.str()
	}

	w.write_string('\treturn ${return_expr(ret, 'result', f.raw, f.v_ret)}\n}\n')
	return w.str()
}

// return_expr is the final `return` of a trampoline.
//
// A raw result is a `voidptr` the V side already owns a reference to, so it is
// wrapped as-is without touching the reference count. Everything else is a real
// V value that has to be boxed. `v_type` is the declared value type, which a
// sequence needs to choose how each element is boxed.
pub fn return_expr(strategy Strategy, value string, raw bool, v_type string) string {
	if raw {
		// A raw function hands back a borrowed pointer, so the wrapper takes the
		// reference itself. Without this the caller receives a pointer it never
		// owned and CPython over-decrements it at teardown, which crashes the
		// interpreter on exit rather than at the call.
		return "vcraft.borrow(${value}).new_ref().ptr"
	}
	// `boxed_expr` already produces an expression that yields the object, except for
	// `.pyref`, where it is the object itself rather than a pointer to one.
	return match strategy {
		.pyref { boxed_expr(strategy, value) + '.ptr' }
		// A `voidptr` result is borrowed, the same contract as a raw one, and it is
		// already a pointer: boxing it and taking `.ptr` does not compile.
		.pyobj { 'vcraft.borrow(${value}).new_ref().ptr' }
		.seq { '${seq_boxed_expr(element_type(v_type), value)}.ptr' }
		else { '${boxed_expr(strategy, value)}.ptr' }
	}
}

// seq_boxed_expr boxes a returned `[]T` as a list. Slices of the plain number types
// the runtime has a one-pass builder for use it; every other element type goes through
// `to_py_list` with a boxing rule.
fn seq_boxed_expr(element string, value string) string {
	return match element {
		'i64' { 'vcraft.to_py_i64_list(${value})' }
		'int' { 'vcraft.to_py_int_list(${value})' }
		'f64' { 'vcraft.to_py_f64_list(${value})' }
		else { 'vcraft.to_py_list(${value}, ${element_box_fn(element)})' }
	}
}

// element_box_fn renders the boxing rule `vcraft.to_py_list` applies to each element
// of a returned `[]T`, as an anonymous function from `T` to an object.
//
// The runtime cannot pick the rule itself: the element type is only known here. Each
// rule widens to the one width its boxer takes, so every integer width shares
// `to_py_int`. An element with no rule is refused by `validate` before this runs.
pub fn element_box_fn(element string) string {
	boxed := match lookup(element) {
		.int { 'vcraft.to_py_int(i64(x))' }
		.uint { 'vcraft.to_py_uint(u64(x))' }
		.float { 'vcraft.to_py_f64(f64(x))' }
		.str { 'vcraft.to_py_string(x)' }
		.bool { 'vcraft.to_py_bool(x)' }
		else { 'vcraft.to_py_none()' }
	}
	return 'fn (x ${element}) vcraft.PyObj { return ${boxed} }'
}

// element_is_boxable reports whether a returned `[]T` has an element rule.
pub fn element_is_boxable(element string) bool {
	return lookup(element) in [.int, .uint, .float, .str, .bool]
}

// element_is_readable reports whether a `[]T` parameter has an element reader.
//
// `[]u8` never reaches this: it is a buffer, read through the buffer protocol
// rather than as a sequence.
pub fn element_is_readable(element string) bool {
	if element == 'u8' {
		return false
	}
	return lookup(element) in [.int, .uint, .float, .str, .bool]
}

// zero_value is the initial value of a result local. It has to be valid V for the
// declared type, which rules out `T(0)` for strings and slices. A uint result
// starts as `u64(0)` rather than `0`: the local is assigned the declared width
// before it is boxed, and `to_py_uint` takes nothing narrower.
pub fn zero_value(strategy Strategy, v_type string) string {
	return match strategy {
		.void { 'unsafe { nil }' }
		.bool { 'false' }
		.int { '0' }
		.uint { 'u64(0)' }
		.float { '0.0' }
		.str { "''" }
		// `.bytes` is always a `[]u8`: a string literal would not compile where a slice
		// is declared.
		.bytes { '[]u8{}' }
		.pyref { 'vcraft.null' }
		.seq { '${v_type}{}' }
		.pyobj, .unsupported { 'unsafe { nil }' }
	}
}

// scalar_narrower names the runtime converter for a scalar narrower than the width its
// strategy reads (`int`, `u64`, `f64`), or returns '' when the plain reader fits.
fn scalar_narrower(v_type string) string {
	return match v_type {
		'i8' { 'i8_from_py_int' }
		'i16' { 'i16_from_py_int' }
		'i32' { 'i32_from_py_int' }
		'rune' { 'rune_from_py_int' }
		'u8' { 'u8_from_py_uint' }
		'u16' { 'u16_from_py_uint' }
		'u32' { 'u32_from_py_uint' }
		'f32' { 'f32_from_py_f64' }
		else { '' }
	}
}

// reader_expr returns the statement that reads positional argument `index` into the
// local `local`, with the V type a Python value maps onto.
//
// Every converting branch ends in `or { return unsafe { nil } }`, because the reader
// raises the Python exception itself and the trampoline only has to notice that
// something is pending.
pub fn reader_expr(strategy Strategy, local string, index int, func string, param string,
	param_type string) string {
	// A width narrower than the reader's result does not convert implicitly in V:
	// `i8`, `i16`, `i32`, `u8`, `u16`, `u32` and `f32` parameters generated glue that
	// did not compile. They read the object and go through the same range-checked
	// narrower their sequences use, so an out-of-range value raises OverflowError.
	narrower := scalar_narrower(param_type.trim_space())
	call := match strategy {
		.bool { "vcraft.from_py_bool_arg(args, ${index}, '${func}', '${param}')" }
		.int, .uint, .float {
			if narrower.len > 0 {
				"vcraft.${narrower}(vcraft.required_arg(args, ${index}, '${func}', '${param}') or { return unsafe { nil } }, '${param}')"
			} else if strategy == .int {
				"vcraft.from_py_int_arg(args, ${index}, '${func}', '${param}')"
			} else if strategy == .uint {
				"vcraft.from_py_uint_arg(args, ${index}, '${func}', '${param}')"
			} else {
				"vcraft.from_py_f64_arg(args, ${index}, '${func}', '${param}')"
			}
		}
		.str { "vcraft.from_py_string_arg(args, ${index}, '${func}', '${param}')" }
		// A `[]u8` parameter takes any bytes-like object without copying it. Exact
		// `bytes` aliases the object with no view at all; anything else goes
		// through a view whose deferred release pins the exporter for the call.
		// The slice must not outlive the call, because the release drops the
		// exporter's reference.
		.bytes {
			"\t${local}_bytes := vcraft.bytes_arg(args, ${index}, '${func}', '${param}') or { return unsafe { nil } }\n" +
				'\tdefer { ${local}_bytes.release() }\n' +
				'\t${local} := ${local}_bytes.data'
		}
		.seq {
			element := element_type(param_type)
			match lookup(element) {
				// An `i64` element has its own reader: V does not convert a `[]int` into
				// a `[]i64`, so the int reader's result does not compile there. The
				// narrower widths have theirs for the same reason; only `int` itself
				// uses the one-pass C reader.
				.int {
					if element == 'i64' {
						"vcraft.from_py_i64_seq_arg(args, ${index}, '${func}', '${param}')"
					} else if element == 'int' {
						"vcraft.from_py_int_seq_arg(args, ${index}, '${func}', '${param}')"
					} else {
						"vcraft.from_py_${element}_seq_arg(args, ${index}, '${func}', '${param}')"
					}
				}
				.uint {
					if element == 'u64' {
						"vcraft.from_py_uint_seq_arg(args, ${index}, '${func}', '${param}')"
					} else {
						"vcraft.from_py_${element}_seq_arg(args, ${index}, '${func}', '${param}')"
					}
				}
				.float {
					if element == 'f64' {
						"vcraft.from_py_f64_seq_arg(args, ${index}, '${func}', '${param}')"
					} else {
						"vcraft.from_py_${element}_seq_arg(args, ${index}, '${func}', '${param}')"
					}
				}
				.str { "vcraft.from_py_str_seq_arg(args, ${index}, '${func}', '${param}')" }
				.bool { "vcraft.from_py_bool_seq_arg(args, ${index}, '${func}', '${param}')" }
				else { "vcraft.from_py_int_seq_arg(args, ${index}, '${func}', '${param}')" }
			}
		}
		.pyobj {
			// A `voidptr` parameter, so the reader hands one over. `require_arg` returns a
			// `PyObj` and relies on V dereferencing the struct into the `voidptr`, which
			// warns and is documented as going away.
			"\t${local} := vcraft.require_voidptr_arg(args, ${index}, '${func}', '${param}')\n" +
				'\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}'
		}
		else {
			"\t${local} := vcraft.require_arg(args, ${index}, '${func}', '${param}')\n" +
				'\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}'
		}
	}
	// `.bytes` renders its own statements -- acquire, deferred release, alias -- so
	// like the other multi-line readers it is returned whole rather than wrapped in an
	// assignment it already contains.
	if strategy == .pyobj || strategy == .pyref || strategy == .bytes || strategy == .unsupported {
		return call
	}
	return '${local} := ${call} or { return unsafe { nil } }'
}

// python_signature renders `name(a: int, b: int) -> int` for `__text_signature__`.
pub fn python_signature(f Func) string {
	return '${f.name}(${param_list(f)}) -> ${describe(f.v_ret)}'
}

fn param_list(f Func) string {
	mut parts := []string{}
	for param in f.params {
		parts << '${param.name}: ${describe(param.v_type)}'
	}
	return parts.join(', ')
}

// boxed_expr returns the expression that boxes a V value as a Python object.
pub fn boxed_expr(strategy Strategy, value string) string {
	return match strategy {
		.void { 'vcraft.to_py_none()' }
		.bool { 'vcraft.to_py_bool(' + value + ')' }
		.int { 'vcraft.to_py_int(' + value + ')' }
		.uint { 'vcraft.to_py_uint(' + value + ')' }
		.float { 'vcraft.to_py_f64(' + value + ')' }
		.str { 'vcraft.to_py_string(' + value + ')' }
		// Copying: a Python `bytes` owns immutable storage, so there is nothing to
		// alias a V slice into. Reads cost nothing; writes pay for the type.
		.bytes { 'vcraft.to_py_bytes_slice(' + value + ')' }
		.seq { 'vcraft.to_py_list(' + value + ')' }
		.pyobj { value }
		// The V value owns a reference and CPython steals the one a getter returns, so
		// the ownership moves rather than being copied. `steal` is the spelling of that.
		.pyref { 'vcraft.steal(' + value + '.ptr)' }
		.unsupported { 'unsafe { nil }' }
	}
}

// unbox_expr renders the call that converts an incoming `PyObject *` into the V type
// a field holds. A setter cannot copy the bytes: the object behind an int is a
// `PyLong` with CPython's own layout.
pub fn unbox_expr(strategy Strategy, value string, v_type string) string {
	// A narrow field is converted to its own width, range-checked. Unboxing it at the
	// strategy's width and then copying `sizeof(field)` bytes of that wider local wrote
	// the low bytes of an `f64` into an `f32` field (garbage) and truncated an
	// out-of-range `i8` without a word.
	narrower := scalar_narrower(v_type.trim_space())
	if narrower.len > 0 && strategy in [.int, .uint, .float] {
		return 'vcraft.${narrower}(vcraft.borrow(' + value + '), ' + vstring_literal('value') + ')'
	}
	return match strategy {
		.bool { 'vcraft.unbox_bool(' + value + ')' }
		.int { 'vcraft.unbox_int(' + value + ', ' + vstring_literal('value') + ')' }
		.uint { 'vcraft.unbox_uint(' + value + ', ' + vstring_literal('value') + ')' }
		.float { 'vcraft.unbox_f64(' + value + ', ' + vstring_literal('value') + ')' }
		// Borrowed, because the caller keeps its own reference to whatever it passed.
		// The value it ends up in is released with `decref` or handed to a field, which
		// counts it.
		.pyref { 'vcraft.borrow(' + value + ')' }
		else { 'vcraft.unbox_int(' + value + ', ' + vstring_literal('value') + ')' }
	}
}

// py_repr_expr renders a V expression that produces the Python repr of a value.
pub fn py_repr_expr(strategy Strategy, value string) string {
	return match strategy {
		.bool { 'vcraft.repr_bool(' + value + ')' }
		.int { 'vcraft.repr_int(' + value + ')' }
		.uint { 'vcraft.repr_uint(' + value + ')' }
		.float { 'vcraft.repr_f64(' + value + ')' }
		.str { 'vcraft.repr_string(' + value + ')' }
		else { "'...'" }
	}
}

// The bytes that have to be escaped inside a single-quoted V literal.
const esc_backslash = u8(92)

const esc_quote = u8(39)

const esc_newline = u8(10)

const esc_return = u8(13)

const esc_tab = u8(9)

// vstring_literal renders a V string literal, escaping what V needs escaped.
//
// A docstring arrives from the user's source as plain text and may hold a quote, a
// backslash or a newline, any of which would otherwise end the literal early.
pub fn vstring_literal(text string) string {
	mut w := new_builder()
	w.write_string("'")
	for ch in text {
		if ch == esc_backslash {
			w.write_string('\\\\')
		} else if ch == esc_quote {
			w.write_string("\\'")
		} else if ch == esc_newline {
			w.write_string('\\n')
		} else if ch == esc_return {
			w.write_string('\\r')
		} else if ch == esc_tab {
			w.write_string('\\t')
		} else {
			w.write_u8(ch)
		}
	}
	w.write_string("'")
	return w.str()
}

// emit_stubs renders the `.pyi` type stub for a project.
pub fn emit_stubs(p Project) string {
	mut w := new_builder()
	w.write_string('# Generated by vcraft. Do not edit.\n')
	w.write_string('# Regenerate with `vcraft build`.\n\n')
	w.write_string('from typing import Any, Sequence\n')
	for f in p.funcs {
		w.write_string('\n')
		if f.doc.len > 0 {
			w.write_string('${indent_doc(f.doc)}\n')
		}
		w.write_string('def ${f.name}(${param_list(f)}) -> ${describe(f.v_ret)}: ...\n')
	}
	for c in p.classes {
		w.write_string('\n')
		if c.doc.len > 0 {
			w.write_string('${indent_doc(c.doc)}\n')
		}
		// The base is in the declaration because it is in the type: a stub that said
		// `class BoundedCounter:` would type-check `b.value` as an error, since the stub
		// has no base to inherit the field from.
		if c.base_index >= 0 {
			w.write_string('class ${c.name}(${c.base}):\n')
		} else {
			w.write_string('class ${c.name}:\n')
		}
		// Fields come first and are attributes rather than methods: that is what they
		// are at runtime, and a stub that declared them as methods would type-check
		// `c.value` as a bound method. Only this class's own fields: the stub's base
		// declaration already accounts for the inherited ones.
		for field in c.fields {
			w.write_string('    ${field.name}: ${describe(field.v_type)}\n')
		}
		for method in c.methods {
			if method.property {
				w.write_string('    @property\n')
			}
			w.write_string('    def ${method.name}(self${method_params(method)}) -> ' +
				'${describe(method.v_ret)}: ...\n')
		}
	}
	return w.str()
}

fn method_params(f Func) string {
	if f.params.len == 0 {
		return ''
	}
	return ', ' + param_list(f)
}

// indent_doc re-indents a doc comment as a Python docstring.
fn indent_doc(doc string) string {
	lines := doc.split('\n')
	if lines.len == 1 {
		return '"""${lines[0]}"""'
	}
	mut out := '"""${lines[0]}\n'
	for line in lines[1..] {
		// No trailing whitespace on empty lines: a `\t` alone is invisible in the
		// file, breaks `git diff --check`, and says nothing to a reader.
		out += if line.len > 0 { '\t${line}' } else { '' }
		out += '\n'
	}
	return out + '"""'
}

// element_type returns the element type of a `[]T`, which decides which sequence
// reader the generated code calls.
pub fn element_type(v_type string) string {
	base := v_type.trim_space()
	return if base.starts_with('[]') { base[2..] } else { base }
}
