module vcraft_codegen

// Emitting the glue.
//
// The output is a V file in the user's own module, so the trampolines call their
// functions directly with no module prefix and no cross-module edge. It is
// ordinary V that a person can read and a person can debug.
//
// The shape of a trampoline is fixed. For a plain function:
//
//	fn vcraft_generated__wrap_add(self voidptr, args voidptr, nargs isize) voidptr {
//		vcraft.require_nargs('add', 2, int(nargs))
//		if vcraft.error_is_set() { return unsafe { nil } }
//		arg0 := vcraft.from_py_int_arg(args, 0, 'add', 'a') or { return unsafe { nil } }
//		arg1 := vcraft.from_py_int_arg(args, 1, 'add', 'b') or { return unsafe { nil } }
//		vcraft.reject_extra_args('add', 2, int(nargs))
//		if vcraft.error_is_set() { return unsafe { nil } }
//		mut result := 0
//		defer { if message := recover() { vcraft.raise_runtime_error('panic in V code: ${message}') } }
//		result = add(arg0, arg1)
//		if vcraft.error_is_set() { return unsafe { nil } }
//		return vcraft.to_py_int(result).ptr
//	}
//
// The `defer` is what keeps a V panic, which calls exit(1), from taking the
// interpreter down. When one fires, `result` keeps its zero value and the
// `error_is_set` check turns that into a Python exception rather than a bogus
// value. Nothing the guard touches needs to survive the jump, because the
// exception state it sets lives on the C side.

import strings

// new_builder returns an empty builder.
//
// V's `strings.Builder.new()` returns the zero value rather than a value, so a
// one-line wrapper is clearer at the many call sites below than the cast is.
fn new_builder() strings.Builder {
	return strings.Builder{}
}

const generated_header = '// Code generated by vcraft. Do not edit.\n' +
	'// Regenerate with `vcraft build`; it is written to disk and overwritten.\n\n'

// emit_glue renders the glue file for a project.
pub fn emit_glue(p Project) string {
	mut w := new_builder()
	w.write_string(generated_header)
	w.write_string('module ${p.module}\n\n')
	w.write_string('import vcraft\n\n')
	w.write_string("@[export: 'PyInit_${p.package}']\n")
	w.write_string('fn vcraft_generated__pyinit() voidptr {\n')
	w.write_string('\tmut m := vcraft.new_module(\'${p.package}\', ' +
		'${vstring_literal(module_docstring(p))})\n')
	for f in p.funcs {
		flags := if f.params.len == 0 { 'vcraft.meth_noargs' } else { 'vcraft.meth_fastcall' }
		w.write_string("\tm.add_function_owned('${f.name}', voidptr(${f.trampoline}), " +
			'${flags},\n\t\t${vstring_literal(python_signature(f))})\n')
	}
	// The module has to exist before anything can be attached to it, so `seal`
	// comes first and the classes go on afterwards.
	w.write_string('\tmodule := m.seal()\n')
	for c in p.classes {
		w.write_string(register_class(c))
	}
	w.write_string('\treturn module.ptr\n}\n')
	for f in p.funcs {
		w.write_string('\n')
		w.write_string(emit_trampoline(f))
	}
	for c in p.classes {
		w.write_string(emit_class(c))
		for m in c.methods {
			w.write_string('\n')
			if m.property {
				w.write_string(emit_property_trampoline(c, m))
			} else {
				w.write_string(emit_method_trampoline(c, m))
			}
		}
	}
	return w.str()
}

// register_class adds one class to the module being built.
//
// The tables the type needs are module-level globals rather than locals, because
// CPython keeps reading them: `PyType_FromSpec` copies what it needs, but a
// PyMethodDef's name and doc pointers are borrowed for the life of the type.
fn register_class(c Class) string {
	mut w := new_builder()
	w.write_string('\t${c.ctype} := vcraft.new_type(')
	w.write_string("'${c.qualified}',\n")
	w.write_string('\t\t' + vstring_literal(c.doc) + ',\n')
	w.write_string('\t\tvoidptr(${c.ctor}),\n')
	// `tp_init` is left null: the constructor runs in `tp_new`, so a subclass that
	// overrides `__init__` still gets a chance to add to it.
	w.write_string('\t\tunsafe { nil },\n')
	w.write_string('\t\tvoidptr(${c.dealloc}),\n')
	// Taking the address of a mutable array element needs an unsafe block, and both
	// tables are module-level globals that the type borrows for its lifetime.
	if c.methods.any(it.property == false) {
		w.write_string('\t\tunsafe { voidptr(&g_vc_methods_${c.key}[0]) },\n')
	} else {
		w.write_string('\t\tunsafe { nil },\n')
	}
	if c.fields.len > 0 || c.methods.any(it.property) {
		w.write_string('\t\tunsafe { voidptr(&g_vc_getsets_${c.key}[0]) },\n')
	} else {
		w.write_string('\t\tunsafe { nil },\n')
	}
	w.write_string('\t\tvoidptr(${c.repr}),\n')
	w.write_string('\t)\n')
	w.write_string("\tvcraft.add_object_ref_on(module, '${c.name}', ${c.ctype})\n")
	return w.str()
}

// emit_method_trampoline renders a method of a class.
//
// It is the ordinary trampoline wrapped in the two statements that move the V value
// in and out of the instance's state block.
pub fn emit_method_trampoline(c Class, f Func) string {
	mut w := new_builder()
	signature := if f.params.len == 0 {
		'self voidptr, args voidptr'
	} else {
		'self voidptr, args voidptr, nargs isize'
	}
	w.write_string('fn ${f.trampoline}(${signature}) voidptr {\n')
	if f.params.len > 0 {
		w.write_string("\tvcraft.require_nargs('${f.name}', ${f.params.len}, int(nargs))\n")
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
	}
	mut names := []string{}
	for i, param in f.params {
		name := local_name(i)
		names << name
		w.write_string('\t${reader_expr(lookup(param.v_type), name, i, f.name, param.name, param.v_type)}\n')
	}
	if f.params.len > 0 {
		w.write_string("\tvcraft.reject_extra_args('${f.name}', ${f.params.len}, int(nargs))\n")
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
	}
	w.write_string('\tmut state := ${c.name}{}\n')
	w.write_string('\tvcraft.load_state(vcraft.instance_storage(self), voidptr(&state), ' +
		'${c.size_fn}())\n')
	ret := lookup(f.v_ret)
	has_value := ret != .void
	if has_value {
		w.write_string('\tmut result := ${zero_value(ret, f.v_ret)}\n')
	}
	w.write_string('\tdefer {\n')
	w.write_string('\t\tif message := recover() {\n')
	w.write_string("\t\t\tvcraft.raise_runtime_error('panic in V code: \${message}')\n")
	w.write_string('\t\t}\n')
	w.write_string('\t}\n')
	call := if f.params.len == 0 { 'state.${f.name}()' } else { 'state.${f.name}(${names.join(', ')})' }
	if f.returns_result {
		inner := 'vcraft.raise_from_error(err)\n\t\treturn unsafe { nil }'
		if has_value {
			w.write_string('\tresult := ${call} or {\n\t\t${inner}\n\t}\n')
		} else {
			w.write_string('\t${call} or {\n\t\t${inner}\n\t}\n')
		}
	} else if has_value {
		w.write_string('\tresult = ${call}\n')
	} else {
		w.write_string('\t${call}\n')
	}
	// The instance is written back before anything can fail, so a method that
	// raises leaves the object consistent.
	w.write_string('\tvcraft.store_state(voidptr(&state), vcraft.instance_storage(self), ' +
		'${c.size_fn}())\n')
	w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
	if has_value {
		w.write_string('\treturn ${return_expr(ret, 'result', false)}\n')
	} else {
		w.write_string('\treturn vcraft.to_py_none().ptr\n')
	}
	w.write_string('}\n')
	return w.str()
}

// emit_property_trampoline renders a method exposed as a Python property.
//
// A getter is called with the instance and the descriptor closure, not with an
// argument tuple, and it must take no arguments.
pub fn emit_property_trampoline(c Class, f Func) string {
	mut w := new_builder()
	w.write_string('fn ${f.trampoline}(self voidptr, closure voidptr) voidptr {\n')
	w.write_string('\tmut state := ${c.name}{}\n')
	w.write_string('\tvcraft.load_state(vcraft.instance_storage(self), voidptr(&state), ' +
		'${c.size_fn}())\n')
	ret := lookup(f.v_ret)
	w.write_string('\tdefer {\n')
	w.write_string('\t\tif message := recover() {\n')
	w.write_string("\t\t\tvcraft.raise_runtime_error('panic in V code: \${message}')\n")
	w.write_string('\t\t}\n')
	w.write_string('\t}\n')
	if f.returns_result {
		inner := 'vcraft.raise_from_error(err)\n\treturn unsafe { nil }'
		w.write_string('\tresult := state.${f.name}() or {\n\t${inner}\n\t}\n')
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
		w.write_string('\treturn ${return_expr(ret, 'result', false)}\n')
	} else {
		w.write_string('\tresult := state.${f.name}()\n')
		w.write_string('\treturn ${return_expr(ret, 'result', false)}\n')
	}
	w.write_string('}\n')
	return w.str()
}

// module_docstring is the module's `__doc__`, taken from the first exported
// function's doc comment since a project has no module-level one of its own.
fn module_docstring(p Project) string {
	for f in p.funcs {
		if f.doc.len > 0 {
			return f.doc.split('\n')[0]
		}
	}
	return '${p.package}, built with vcraft.'
}

// local_name is the generated name for the i-th argument. It is positional rather
// than taken from the V parameter so that two parameters of the same type cannot
// collide, which is what a naive `v :=` per parameter would do.
fn local_name(i int) string {
	return 'arg${i}'
}

// emit_trampoline renders one trampoline.
pub fn emit_trampoline(f Func) string {
	mut w := new_builder()
	signature := if f.params.len == 0 {
		'self voidptr, args voidptr'
	} else {
		'self voidptr, args voidptr, nargs isize'
	}
	w.write_string('fn ${f.trampoline}(${signature}) voidptr {\n')

	if f.params.len > 0 {
		w.write_string("\tvcraft.require_nargs('${f.name}', ${f.params.len}, int(nargs))\n")
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
	}

	// `@[vc_raw]` keeps the declared signature but skips every conversion: each
	// parameter is handed over as the borrowed `PyObject *` itself, and the result
	// is returned as whatever pointer the function produced. The V function owns
	// every reference it touches.
	mut names := []string{}
	for i, param in f.params {
		if f.raw {
			name := local_name(i)
			names << name
			w.write_string('\t${name} := vcraft.from_py_voidptr(' +
				"vcraft.require_arg(args, ${i}, '${f.name}', '${param.name}'))\n")
			w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
			continue
		}
		strategy := lookup(param.v_type)
		name := local_name(i)
		names << name
		w.write_string('\t${reader_expr(strategy, name, i, f.name, param.name, param.v_type)}\n')
	}

	if f.params.len > 0 {
		w.write_string("\tvcraft.reject_extra_args('${f.name}', ${f.params.len}, int(nargs))\n")
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
	}

	ret := lookup(f.v_ret)
	has_value := f.raw || ret != .void

	// The result is declared before the guard so that the call has somewhere to
	// assign even when the guard unwinds past it. A `!T` function declares it with
	// `:=` further down, where the `or` block needs to introduce it.
	if has_value && !f.returns_result {
		w.write_string('\tmut result := ${zero_value(ret, f.v_ret)}\n')
	}
	// A raw function's result is a pointer the V side already owns, so it is
	// handed back without touching the reference count.
	w.write_string('\tdefer {\n')
	w.write_string('\t\tif message := recover() {\n')
	w.write_string("\t\t\tvcraft.raise_runtime_error('panic in V code: \${message}')\n")
	w.write_string('\t\t}\n')
	w.write_string('\t}\n')

	call := if f.params.len == 0 { '${f.name}()' } else { '${f.name}(${names.join(', ')})' }

	if f.returns_result {
		// V has no `is` test for a Result, so error propagation is the mechanism:
		// the `or` block receives `err` directly and turns it into a Python
		// exception before returning.
		inner := 'vcraft.raise_from_error(err)\n\t\treturn unsafe { nil }'
		if has_value {
			w.write_string('\tresult := ${call} or {\n\t\t${inner}\n\t}\n')
		} else {
			w.write_string('\t${call} or {\n\t\t${inner}\n\t}\n')
		}
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
	} else {
		if has_value {
			w.write_string('\tresult = ${call}\n')
		} else {
			w.write_string('\t${call}\n')
		}
		w.write_string('\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}\n')
		if has_value {
			w.write_string('\treturn ${return_expr(ret, 'result', f.raw)}\n')
		} else {
			w.write_string('\treturn vcraft.to_py_none().ptr\n')
		}
		w.write_string('}\n')
		return w.str()
	}

	w.write_string('\treturn ${return_expr(ret, 'result', f.raw)}\n}\n')
	return w.str()
}

// return_expr is the final `return` of a trampoline.
//
// A raw result is a `voidptr` the V side already owns a reference to, so it is
// wrapped as-is without touching the reference count. Everything else is a real
// V value that has to be boxed.
pub fn return_expr(strategy Strategy, value string, raw bool) string {
	if raw {
		// A raw function hands back a borrowed pointer, so the wrapper takes the
		// reference itself. Without this the caller receives a pointer it never
		// owned and CPython over-decrements it at teardown, which crashes the
		// interpreter on exit rather than at the call.
		return "vcraft.borrow(${value}).new_ref().ptr"
	}
	return '${boxed_expr(strategy, value)}.ptr'
}

// zero_value is the initial value of a result local. It has to be valid V for the
// declared type, which rules out `T(0)` for strings and slices.
pub fn zero_value(strategy Strategy, v_type string) string {
	return match strategy {
		.void { 'unsafe { nil }' }
		.bool { 'false' }
		.int, .uint { '0' }
		.float { '0.0' }
		.str, .bytes { "''" }
		.seq { '${v_type}{}' }
		.pyobj, .unsupported { 'unsafe { nil }' }
	}
}

// reader_expr returns the statement that reads positional argument `index` into the
// local `local`, with the V type a Python value maps onto.
//
// Every converting branch ends in `or { return unsafe { nil } }`, because the reader
// raises the Python exception itself and the trampoline only has to notice that
// something is pending.
pub fn reader_expr(strategy Strategy, local string, index int, func string, param string,
	param_type string) string {
	call := match strategy {
		.bool { "vcraft.from_py_bool_arg(args, ${index}, '${func}', '${param}')" }
		.int { "vcraft.from_py_int_arg(args, ${index}, '${func}', '${param}')" }
		.uint { "vcraft.from_py_uint_arg(args, ${index}, '${func}', '${param}')" }
		.float { "vcraft.from_py_f64_arg(args, ${index}, '${func}', '${param}')" }
		.str { "vcraft.from_py_string_arg(args, ${index}, '${func}', '${param}')" }
		.bytes { "vcraft.from_py_bytes_arg(args, ${index}, '${func}', '${param}')" }
		.seq {
			element := element_type(param_type)
			match lookup(element) {
				.int { "vcraft.from_py_int_seq_arg(args, ${index}, '${func}', '${param}')" }
				.uint { "vcraft.from_py_uint_seq_arg(args, ${index}, '${func}', '${param}')" }
				.float { "vcraft.from_py_f64_seq_arg(args, ${index}, '${func}', '${param}')" }
				.str { "vcraft.from_py_str_seq_arg(args, ${index}, '${func}', '${param}')" }
				else { "vcraft.from_py_int_seq_arg(args, ${index}, '${func}', '${param}')" }
			}
		}
		else {
			"\t${local} := vcraft.require_arg(args, ${index}, '${func}', '${param}')\n" +
				'\tif vcraft.error_is_set() {\n\t\treturn unsafe { nil }\n\t}'
		}
	}
	if strategy == .pyobj || strategy == .unsupported {
		return call
	}
	return '${local} := ${call} or { return unsafe { nil } }'
}

// python_signature renders `name(a: int, b: int) -> int` for `__text_signature__`.
pub fn python_signature(f Func) string {
	return '${f.name}(${param_list(f)}) -> ${describe(f.v_ret)}'
}

fn param_list(f Func) string {
	mut parts := []string{}
	for param in f.params {
		parts << '${param.name}: ${describe(param.v_type)}'
	}
	return parts.join(', ')
}

// boxed_expr returns the expression that boxes a V value as a Python object.
pub fn boxed_expr(strategy Strategy, value string) string {
	return match strategy {
		.void { 'vcraft.to_py_none()' }
		.bool { 'vcraft.to_py_bool(' + value + ')' }
		.int { 'vcraft.to_py_int(' + value + ')' }
		.uint { 'vcraft.to_py_uint(' + value + ')' }
		.float { 'vcraft.to_py_f64(' + value + ')' }
		.str { 'vcraft.to_py_string(' + value + ')' }
		.bytes { 'vcraft.to_py_bytes(' + value + ')' }
		.seq { 'vcraft.to_py_list(' + value + ')' }
		.pyobj { value }
		.unsupported { 'unsafe { nil }' }
	}
}

// unbox_expr renders the call that converts an incoming `PyObject *` into the V type
// a field holds. A setter cannot copy the bytes: the object behind an int is a
// `PyLong` with CPython's own layout.
pub fn unbox_expr(strategy Strategy, value string) string {
	return match strategy {
		.bool { 'vcraft.unbox_bool(' + value + ')' }
		.int { 'vcraft.unbox_int(' + value + ', ' + vstring_literal('value') + ')' }
		.uint { 'vcraft.unbox_uint(' + value + ', ' + vstring_literal('value') + ')' }
		.float { 'vcraft.unbox_f64(' + value + ', ' + vstring_literal('value') + ')' }
		else { 'vcraft.unbox_int(' + value + ', ' + vstring_literal('value') + ')' }
	}
}

// py_repr_expr renders a V expression that produces the Python repr of a value.
pub fn py_repr_expr(strategy Strategy, value string) string {
	return match strategy {
		.bool { 'vcraft.repr_bool(' + value + ')' }
		.int { 'vcraft.repr_int(' + value + ')' }
		.uint { 'vcraft.repr_uint(' + value + ')' }
		.float { 'vcraft.repr_f64(' + value + ')' }
		.str { 'vcraft.repr_string(' + value + ')' }
		else { "'...'" }
	}
}

// The bytes that have to be escaped inside a single-quoted V literal.
const esc_backslash = u8(92)

const esc_quote = u8(39)

const esc_newline = u8(10)

const esc_return = u8(13)

const esc_tab = u8(9)

// vstring_literal renders a V string literal, escaping what V needs escaped.
//
// A docstring arrives from the user's source as plain text and may hold a quote, a
// backslash or a newline, any of which would otherwise end the literal early.
pub fn vstring_literal(text string) string {
	mut w := new_builder()
	w.write_string("'")
	for ch in text {
		if ch == esc_backslash {
			w.write_string('\\\\')
		} else if ch == esc_quote {
			w.write_string("\\'")
		} else if ch == esc_newline {
			w.write_string('\\n')
		} else if ch == esc_return {
			w.write_string('\\r')
		} else if ch == esc_tab {
			w.write_string('\\t')
		} else {
			w.write_u8(ch)
		}
	}
	w.write_string("'")
	return w.str()
}

// emit_stubs renders the `.pyi` type stub for a project.
pub fn emit_stubs(p Project) string {
	mut w := new_builder()
	w.write_string('# Generated by vcraft. Do not edit.\n')
	w.write_string('# Regenerate with `vcraft build`.\n\n')
	w.write_string('from typing import Any, Sequence\n')
	for f in p.funcs {
		w.write_string('\n')
		if f.doc.len > 0 {
			w.write_string('${indent_doc(f.doc)}\n')
		}
		w.write_string('def ${f.name}(${param_list(f)}) -> ${describe(f.v_ret)}: ...\n')
	}
	for c in p.classes {
		w.write_string('\n')
		if c.doc.len > 0 {
			w.write_string('${indent_doc(c.doc)}\n')
		}
		w.write_string('class ${c.name}:\n')
		// Fields come first and are attributes rather than methods: that is what they
		// are at runtime, and a stub that declared them as methods would type-check
		// `c.value` as a bound method.
		for field in c.fields {
			w.write_string('    ${field.name}: ${describe(field.v_type)}\n')
		}
		for method in c.methods {
			if method.property {
				w.write_string('    @property\n')
			}
			w.write_string('    def ${method.name}(self${method_params(method)}) -> ' +
				'${describe(method.v_ret)}: ...\n')
		}
	}
	return w.str()
}

fn method_params(f Func) string {
	if f.params.len == 0 {
		return ''
	}
	return ', ' + param_list(f)
}

// indent_doc re-indents a doc comment as a Python docstring.
fn indent_doc(doc string) string {
	lines := doc.split('\n')
	if lines.len == 1 {
		return '"""${lines[0]}"""'
	}
	mut out := '"""${lines[0]}\n'
	for line in lines[1..] {
		out += if line.len > 0 { '\t${line}' } else { '\t' }
		out += '\n'
	}
	return out + '"""'
}

// element_type returns the element type of a `[]T`, which decides which sequence
// reader the generated code calls.
pub fn element_type(v_type string) string {
	base := v_type.trim_space()
	return if base.starts_with('[]') { base[2..] } else { base }
}
